require 'open-uri'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Photo.destroy_all
Comment.destroy_all
Follow.destroy_all

user1 = User.create!(email: 'doh@mail.com', password: 'hunter2020', username: 'dohmain', fname: 'Joe', lname: 'Doh')
user2 = User.create!(email: 'krapman@mail.com', password: 'hunter2020', username: 'kraPmaN', fname: 'Nam', lname: 'Park')
user3 = User.create!(email: 'neo@matrix', password: 'hunter2020', username: 'Neo', fname: 'Thomas', lname: 'Anderson')
user4 = User.create!(email: 'jules@pulp.com', password: 'hunter2020', username: 'The Shepherd', fname: 'Jules', lname: 'Winnfield')
user5 = User.create!(email: 'kiddo@mail.com', password: 'hunter2020', username: 'The Bride', fname: 'Beatrix', lname: 'Kiddo')
user6 = User.create!(email: 'stanlee@marvel.com', password: 'hunter2020', username: 'Godfather', fname: 'Stan', lname: 'Lee')
user7 = User.create!(email: 'wolverine@xmen.com', password: 'hunter2020', username: 'Wolverine', fname: 'Logan', lname: 'Fowler')
user8 = User.create!(email: 'tony@stark.com', password: 'hunter2020', username: 'Ironman', fname: 'Tony', lname: 'Stark')
user9 = User.create!(email: 'widow@avengers.com', password: 'hunter2020', username: 'Black Widow', fname: 'Natasha', lname: 'Romanova')
user10 = User.create!(email: 'selene@coven.com', password: 'hunter2020', username: 'Death Dealer', fname: 'Selene', lname: 'Corbin')
user11 = User.create!(email: 'kapow@darkhorse.com', password: 'hunter2020', username: 'Wonder Woman', fname: 'Diana', lname: 'Prince')
user12 = User.create!(email: 'demo@demo.com', password: 'hunter2020', username: 'Demolition Man', fname: 'Demo', lname: 'User')

Follow.create!(follower_id: user1.id, followed_id: user2.id) # check if the fields are correct~~~

px1 = Photo.create!(title: 'Canadian National Parks playing cards', description: 'white and blue playing cards on brown dried leaves', creator_id: user1.id, unsplashURL: 'https://unsplash.com/photos/kXF5CdmJh88', unsplashUserURL: 'https://unsplash.com/@lureofadventure', unsplashName: 'Ali Kazal')
file1 = open('https://perfectpx-seeds.s3.amazonaws.com/ali-kazal-kXF5CdmJh88-unsplash.jpg')
px1.px.attach(io: file1, filename: 'ali-kazal-kXF5CdmJh88-unsplash.jpg')
Comment.create!(user_id: user2.id, photo_id: px1.id, body: 'awesome picture!')
Comment.create!(user_id: user5.id, photo_id: px1.id, body: 'Marvelous')
Comment.create!(user_id: user7.id, photo_id: px1.id, body: 'Amazing work! Very inspiring')
Comment.create!(user_id: user12.id, photo_id: px1.id, body: 'Stunning capture')
Comment.create!(user_id: user11.id, photo_id: px1.id, body: 'So beautiful nature scenery! Impressive work!')

px2 = Photo.create!(title: 'purrr', description: 'white and brown tabby cat lying on white textile', creator_id: user2.id, unsplashURL: 'https://unsplash.com/photos/jzPbnpoaIHw', unsplashUserURL: 'https://unsplash.com/@alison_wang', unsplashName: 'Alison Wang')
file2 = open('https://perfectpx-seeds.s3.amazonaws.com/alison-wang-jzPbnpoaIHw-unsplash.jpg')
px2.px.attach(io: file2, filename: 'alison-wang-jzPbnpoaIHw-unsplash.jpg')
Comment.create!(user_id: user1.id, photo_id: px2.id, body: 'Excellent photography')
Comment.create!(user_id: user6.id, photo_id: px2.id, body: 'Beautiful shot')
Comment.create!(user_id: user3.id, photo_id: px2.id, body: 'You are doing as wonderful a job')
Comment.create!(user_id: user8.id, photo_id: px2.id, body: 'Absolutely fantastic shot')
Comment.create!(user_id: user10.id, photo_id: px2.id, body: 'very nice photo')

px3 = Photo.create!(title: 'Playing Cards', description: 'person holding playing cards on white table', creator_id: user3.id, unsplashURL: 'https://unsplash.com/photos/S0_Ep9meLFY', unsplashUserURL: 'https://unsplash.com/@andriklangfield', unsplashName: 'Andrik Langfield')
file3 = open('https://perfectpx-seeds.s3.amazonaws.com/andrik-langfield-S0_Ep9meLFY-unsplash.jpg')
px3.px.attach(io: file3, filename: 'andrik-langfield-S0_Ep9meLFY-unsplash.jpg')
Comment.create!(user_id: user4.id, photo_id: px3.id, body: 'That is absolutely sensational')
Comment.create!(user_id: user9.id, photo_id: px3.id, body: 'awesome landscape')
Comment.create!(user_id: user12.id, photo_id: px3.id, body: 'Excellent shot')
Comment.create!(user_id: user7.id, photo_id: px3.id, body: 'Awesome moment')
Comment.create!(user_id: user1.id, photo_id: px3.id, body: 'Wonderful photography')

px4 = Photo.create!(title: 'Fresh Baked', description: 'brown and black pie on black tray', creator_id: user4.id, unsplashURL: 'https://unsplash.com/photos/twni7IlpUDE', unsplashUserURL: 'https://unsplash.com/@anshu18', unsplashName: 'Anshu A')
file4 = open('https://perfectpx-seeds.s3.amazonaws.com/anshu-a-twni7IlpUDE-unsplash.jpg')
px4.px.attach(io: file4, filename: 'anshu-a-twni7IlpUDE-unsplash.jpg')
Comment.create!(user_id: user5.id, photo_id: px4.id, body: 'Fantastic!')
Comment.create!(user_id: user2.id, photo_id: px4.id, body: 'Amazing shot excellent work')
Comment.create!(user_id: user10.id, photo_id: px4.id, body: 'Fantastic light and scenery!')
Comment.create!(user_id: user11.id, photo_id: px4.id, body: 'fantastic photo')
Comment.create!(user_id: user6.id, photo_id: px4.id, body: 'Outstanding work my friend')

px5 = Photo.create!(title: 'Soy Candle', description: 'white and black labeled can', creator_id: user5.id, unsplashURL: 'https://unsplash.com/photos/PxEj7UpS6So', unsplashUserURL: 'https://unsplash.com/@apothecary87', unsplashName: 'Apothecary 87')
file5 = open('https://perfectpx-seeds.s3.amazonaws.com/apothecary-87-PxEj7UpS6So-unsplash.jpg')
px5.px.attach(io: file5, filename: 'apothecary-87-PxEj7UpS6So-unsplash.jpg')
Comment.create!(user_id: user4.id, photo_id: px5.id, body: 'Great and beautiful work!')
Comment.create!(user_id: user8.id, photo_id: px5.id, body: 'Wonderful light and composition')
Comment.create!(user_id: user3.id, photo_id: px5.id, body: 'Fantastic work.')
Comment.create!(user_id: user1.id, photo_id: px5.id, body: 'Gorgeous!')
Comment.create!(user_id: user9.id, photo_id: px5.id, body: 'This is so beautiful!!!')

px6 = Photo.create!(title: 'Jam Session', description: 'white electric guitar on blue guitar amplifier', creator_id: user6.id, unsplashURL: 'https://unsplash.com/photos/cCyojGPS8eQ', unsplashUserURL: 'https://unsplash.com/@bhurnal', unsplashName: 'Bernie Almanzar')
file6 = open('https://perfectpx-seeds.s3.amazonaws.com/bernie-almanzar-cCyojGPS8eQ-unsplash.jpg')
px6.px.attach(io: file6, filename: 'bernie-almanzar-cCyojGPS8eQ-unsplash.jpg')
Comment.create!(user_id: user12.id, photo_id: px6.id, body: 'Outstanding work!')
Comment.create!(user_id: user3.id, photo_id: px6.id, body: 'Stunning colors and silhouette')
Comment.create!(user_id: user9.id, photo_id: px6.id, body: 'Superb shot loved it.')
Comment.create!(user_id: user10.id, photo_id: px6.id, body: 'Fine photo!!!!')
Comment.create!(user_id: user11.id, photo_id: px6.id, body: 'Excellent shot!')

px7 = Photo.create!(title: 'Scales', description: 'black and white round structure', creator_id: user7.id, unsplashURL: 'https://unsplash.com/photos/0PU_KWXi5X8', unsplashUserURL: 'https://unsplash.com/@bilgetekin', unsplashName: 'bilge tekin')
file7 = open('https://perfectpx-seeds.s3.amazonaws.com/bilge-tekin-0PU_KWXi5X8-unsplash.jpg')
px7.px.attach(io: file7, filename: 'bilge-tekin-0PU_KWXi5X8-unsplash.jpg')
Comment.create!(user_id: user2.id, photo_id: px7.id, body: 'Beautifully done!')
Comment.create!(user_id: user8.id, photo_id: px7.id, body: 'Beautiful landscape composition work!')
Comment.create!(user_id: user4.id, photo_id: px7.id, body: 'Fantastic light, mood and composition')
Comment.create!(user_id: user5.id, photo_id: px7.id, body: 'Gorgeous capture, congrats!')
Comment.create!(user_id: user6.id, photo_id: px7.id, body: 'Wowwww!')

px8 = Photo.create!(title: 'Septa', description: 'white and blue train in train station', creator_id: user8.id, unsplashURL: 'https://unsplash.com/photos/9qi0XITgRGw', unsplashUserURL: 'https://unsplash.com/@chrishenryphoto', unsplashName: 'Chris Henry')
file8 = open('https://perfectpx-seeds.s3.amazonaws.com/chris-henry-9qi0XITgRGw-unsplash.jpg')
px8.px.attach(io: file8, filename: 'chris-henry-9qi0XITgRGw-unsplash.jpg')
Comment.create!(user_id: user7.id, photo_id: px8.id, body: 'This is lovely')
Comment.create!(user_id: user1.id, photo_id: px8.id, body: 'Bravo!!!')
Comment.create!(user_id: user10.id, photo_id: px8.id, body: 'Wonderful, my friend!')
Comment.create!(user_id: user12.id, photo_id: px8.id, body: 'Your processing is A+')
Comment.create!(user_id: user2.id, photo_id: px8.id, body: 'Wonderfull picture')

px9 = Photo.create!(title: 'Nature Walk', description: 'white and brown long coated dog on river during daytime', creator_id: user9.id, unsplashURL: 'https://unsplash.com/photos/SORam0z8YXY', unsplashUserURL: 'https://unsplash.com/@dtopkin1', unsplashName: 'Dayne Topkin')
file9 = open('https://perfectpx-seeds.s3.amazonaws.com/dayne-topkin-SORam0z8YXY-unsplash.jpg')
px9.px.attach(io: file9, filename: 'dayne-topkin-SORam0z8YXY-unsplash.jpg')
Comment.create!(user_id: user4.id, photo_id: px9.id, body: 'Magnificent landscape work!')
Comment.create!(user_id: user9.id, photo_id: px9.id, body: 'Extraordinary!!')
Comment.create!(user_id: user3.id, photo_id: px9.id, body: 'Wonderful light and view​, amazing capture​')
Comment.create!(user_id: user5.id, photo_id: px9.id, body: 'So beautiful​')
Comment.create!(user_id: user11.id, photo_id: px9.id, body: 'Fantastic capture!')

px10 = Photo.create!(title: 'Old Books', description: 'blue red and brown textile', creator_id: user10.id, unsplashURL: 'https://unsplash.com/photos/UhaCxfXFmLQ', unsplashUserURL: 'https://unsplash.com/@thegordeev', unsplashName: 'Egor Gordeev')
file10 = open('https://perfectpx-seeds.s3.amazonaws.com/egor-gordeev-UhaCxfXFmLQ-unsplash.jpg')
px10.px.attach(io: file10, filename: 'egor-gordeev-UhaCxfXFmLQ-unsplash.jpg')
Comment.create!(user_id: user6.id, photo_id: px10.id, body: 'Awesome shot, my friend!')
Comment.create!(user_id: user1.id, photo_id: px10.id, body: 'Real masterpiece.')
Comment.create!(user_id: user8.id, photo_id: px10.id, body: 'What an amazing capture!')
Comment.create!(user_id: user11.id, photo_id: px10.id, body: 'Beautiful photo')
Comment.create!(user_id: user3.id, photo_id: px10.id, body: 'Wonderful composition !')

px11 = Photo.create!(title: 'Antique Store', description: 'A unique collector\'s store selling engravings and antique art in the city of Rome, Italy. The frieze and columns around the entrance and shop window date from Ancient Rome.', creator_id: user11.id, unsplashURL: 'https://unsplash.com/photos/NpYCNsJ4sP0', unsplashUserURL: 'https://unsplash.com/@gabiontheroad', unsplashName: 'Gabriella Clare Marino')
file11 = open('https://perfectpx-seeds.s3.amazonaws.com/gabriella-clare-marino-NpYCNsJ4sP0-unsplash.jpg')
px11.px.attach(io: file11, filename: 'gabriella-clare-marino-NpYCNsJ4sP0-unsplash.jpg')
Comment.create!(user_id: user7.id, photo_id: px11.id, body: 'Tremendous')
Comment.create!(user_id: user12.id, photo_id: px11.id, body: 'Great photo!')
Comment.create!(user_id: user2.id, photo_id: px11.id, body: 'Excellent!')
Comment.create!(user_id: user6.id, photo_id: px11.id, body: 'Terrific work')
Comment.create!(user_id: user5.id, photo_id: px11.id, body: 'Amazing shot')

px12 = Photo.create!(title: 'Beach Swing', description: 'swing on the beach', creator_id: user12.id, unsplashURL: 'https://unsplash.com/photos/lQAgbqCnxQI', unsplashUserURL: 'https://unsplash.com/@dzngriffin', unsplashName: 'Griffin Wooldridge')
file12 = open('https://perfectpx-seeds.s3.amazonaws.com/griffin-wooldridge-lQAgbqCnxQI-unsplash.jpg')
px12.px.attach(io: file12, filename: 'griffin-wooldridge-lQAgbqCnxQI-unsplash.jpg')
Comment.create!(user_id: user4.id, photo_id: px12.id, body: 'Great work, I love the color and light in this photo!')
Comment.create!(user_id: user10.id, photo_id: px12.id, body: 'Spectacular')
Comment.create!(user_id: user7.id, photo_id: px12.id, body: 'Magic')
Comment.create!(user_id: user5.id, photo_id: px12.id, body: 'Very beautiful capture')
Comment.create!(user_id: user1.id, photo_id: px12.id, body: 'Gorgeous shot')

px13 = Photo.create!(title: 'Bondi Beach', description: 'https://unsplash.com/photos/F-qWu6lEE3c', creator_id: user1.id, unsplashURL: 'https://unsplash.com/photos/F-qWu6lEE3c', unsplashUserURL: 'https://unsplash.com/@mrqs_g', unsplashName: 'Guillaume Marques')
file13 = open('https://perfectpx-seeds.s3.amazonaws.com/guillaume-marques-F-qWu6lEE3c-unsplash.jpg')
px13.px.attach(io: file13, filename: 'guillaume-marques-F-qWu6lEE3c-unsplash.jpg')
Comment.create!(user_id: user4.id, photo_id: px13.id, body: 'Wow!! Great image with terrific color, depth, detail and light!')
Comment.create!(user_id: user8.id, photo_id: px13.id, body: 'Striking composition')
Comment.create!(user_id: user12.id, photo_id: px13.id, body: 'Very nicely captured.')
Comment.create!(user_id: user5.id, photo_id: px13.id, body: 'Beautifully done!')
Comment.create!(user_id: user11.id, photo_id: px13.id, body: 'Fabulous image')

px14 = Photo.create!(title: 'Winter Bear', description: 'Nationalpark Bayerischer Wald, Germany', creator_id: user2.id, unsplashURL: 'https://unsplash.com/photos/e9mlWK6-4ms', unsplashUserURL: 'https://unsplash.com/@g_leighton', unsplashName: 'Gustavo Leighton')
file14 = open('https://perfectpx-seeds.s3.amazonaws.com/gustavo-leighton-e9mlWK6-4ms-unsplash.jpg')
px14.px.attach(io: file14, filename: 'gustavo-leighton-e9mlWK6-4ms-unsplash.jpg')
Comment.create!(user_id: user8.id, photo_id: px14.id, body: 'Excellent work')
Comment.create!(user_id: user9.id, photo_id: px14.id, body: 'Great photo.')
Comment.create!(user_id: user3.id, photo_id: px14.id, body: 'I love these layers and colors!')
Comment.create!(user_id: user10.id, photo_id: px14.id, body: 'Very difficult to believe this is natural')
Comment.create!(user_id: user6.id, photo_id: px14.id, body: 'Impressive view and scenery!')

px15 = Photo.create!(title: 'Choices', description: 'only gets better from here', creator_id: user3.id, unsplashURL: 'https://unsplash.com/photos/7IQ7TEcOcWU', unsplashUserURL: 'https://unsplash.com/@carrier_lost', unsplashName: 'Ian Taylor')
file15 = open('https://perfectpx-seeds.s3.amazonaws.com/ian-taylor-7IQ7TEcOcWU-unsplash.jpg')
px15.px.attach(io: file15, filename: 'ian-taylor-7IQ7TEcOcWU-unsplash.jpg')
Comment.create!(user_id: user7.id, photo_id: px15.id, body: 'Beautiful photo')
Comment.create!(user_id: user2.id, photo_id: px15.id, body: 'Beautiful light and colors.')
Comment.create!(user_id: user9.id, photo_id: px15.id, body: 'Outstanding image')
Comment.create!(user_id: user12.id, photo_id: px15.id, body: 'wonderful capture!!!')
Comment.create!(user_id: user4.id, photo_id: px15.id, body: 'Perfect shot')

px16 = Photo.create!(title: 'V&A Dundee', description: 'Riverside Esplanade, Dundee, UK', creator_id: user4.id, unsplashURL: 'https://unsplash.com/photos/CIC9LYNLjSs', unsplashUserURL: 'https://unsplash.com/@ilyailford', unsplashName: 'Ilya Ilford')
file16 = open('https://perfectpx-seeds.s3.amazonaws.com/ilya-ilford-CIC9LYNLjSs-unsplash.jpg')
px16.px.attach(io: file16, filename: 'ilya-ilford-CIC9LYNLjSs-unsplash.jpg')
Comment.create!(user_id: user9.id, photo_id: px16.id, body: 'Great shot!')
Comment.create!(user_id: user7.id, photo_id: px16.id, body: 'Fabulous capture')
Comment.create!(user_id: user11.id, photo_id: px16.id, body: 'Beautiful colors, this shot is simply excellent!')
Comment.create!(user_id: user1.id, photo_id: px16.id, body: 'Wonderful colors, Perfect light and mood! Very nice!')
Comment.create!(user_id: user3.id, photo_id: px16.id, body: 'Impressive view and scenery!')

px17 = Photo.create!(title: 'Large', description: 'person holding ice cream cone', creator_id: user5.id, unsplashURL: 'https://unsplash.com/photos/LLrohGLmfAg', unsplashUserURL: 'https://unsplash.com/@ilyailford', unsplashName: 'Ilya Ilford')
file17 = open('https://perfectpx-seeds.s3.amazonaws.com/ilya-ilford-LLrohGLmfAg-unsplash.jpg')
px17.px.attach(io: file17, filename: 'ilya-ilford-LLrohGLmfAg-unsplash.jpg')
Comment.create!(user_id: user2.id, photo_id: px17.id, body: 'Great timing!')
Comment.create!(user_id: user8.id, photo_id: px17.id, body: 'Outstanding!')
Comment.create!(user_id: user6.id, photo_id: px17.id, body: 'Looks flat to me')
Comment.create!(user_id: user10.id, photo_id: px17.id, body: 'Uncommon view')
Comment.create!(user_id: user1.id, photo_id: px17.id, body: 'Impressive view and scenery!')

px18 = Photo.create!(title: 'Mushroom', description: 'red and white mushroom in close up', creator_id: user6.id, unsplashURL: 'https://unsplash.com/photos/ilpuew6tl0g', unsplashUserURL: 'https://unsplash.com/@ingmarr', unsplashName: 'Ingmar')
file18 = open('https://perfectpx-seeds.s3.amazonaws.com/ingmar-ilpuew6tl0g-unsplash.jpg')
px18.px.attach(io: file18, filename: 'ingmar-ilpuew6tl0g-unsplash.jpg')
Comment.create!(user_id: user7.id, photo_id: px18.id, body: 'Great comp')
Comment.create!(user_id: user11.id, photo_id: px18.id, body: 'Amazing shot')
Comment.create!(user_id: user5.id, photo_id: px18.id, body: 'Fabulous capture')
Comment.create!(user_id: user2.id, photo_id: px18.id, body: 'Exellent capture and colors.')
Comment.create!(user_id: user3.id, photo_id: px18.id, body: 'Wonderful capture:)')

px19 = Photo.create!(title: 'Mooo', description: 'brown and white fur textile', creator_id: user7.id, unsplashURL: 'https://unsplash.com/photos/xtrGfDhOqxQ', unsplashUserURL: 'https://unsplash.com/@eyefish73', unsplashName: 'Jon Sailer')
file19 = open('https://perfectpx-seeds.s3.amazonaws.com/jon-sailer-xtrGfDhOqxQ-unsplash.jpg')
px19.px.attach(io: file19, filename: 'jon-sailer-xtrGfDhOqxQ-unsplash.jpg')
Comment.create!(user_id: user4.id, photo_id: px19.id, body: 'Very Beautiful. Have a nice day my friend.')
Comment.create!(user_id: user6.id, photo_id: px19.id, body: 'Beautiful POV and capture')
Comment.create!(user_id: user10.id, photo_id: px19.id, body: 'Truly impressed with your attention catching photograph')
Comment.create!(user_id: user12.id, photo_id: px19.id, body: 'Great scene')
Comment.create!(user_id: user8.id, photo_id: px19.id, body: 'Superb shot')

px20 = Photo.create!(title: 'Yellow Ferrari', description: 'yellow Ferrari 458 parked on th street during daytime', creator_id: user8.id, unsplashURL: 'https://unsplash.com/photos/QNwaS0UYSxI', unsplashUserURL: 'https://unsplash.com/@visuallert', unsplashName: 'Jonas Allert')
file20 = open('https://perfectpx-seeds.s3.amazonaws.com/jonas-allert-QNwaS0UYSxI-unsplash.jpg')
px20.px.attach(io: file20, filename: 'jonas-allert-QNwaS0UYSxI-unsplash.jpg')
Comment.create!(user_id: user9.id, photo_id: px20.id, body: 'Magnificent picture excellent work')
Comment.create!(user_id: user3.id, photo_id: px20.id, body: 'Magnificent photo!')
Comment.create!(user_id: user11.id, photo_id: px20.id, body: 'Wonderful light and view​, amazing capture​')
Comment.create!(user_id: user5.id, photo_id: px20.id, body: 'Great shot, beautiful edit')
Comment.create!(user_id: user1.id, photo_id: px20.id, body: 'Excellent shot')

px21 = Photo.create!(title: 'Old School', description: 'black and silver vintage camera', creator_id: user9.id, unsplashURL: 'https://unsplash.com/photos/dKy6K3vfHB8', unsplashUserURL: 'https://unsplash.com/@theshuttervision', unsplashName: 'Jonathan Cooper')
file21 = open('https://perfectpx-seeds.s3.amazonaws.com/jonathan-cooper-dKy6K3vfHB8-unsplash.jpg')
px21.px.attach(io: file21, filename: 'jonathan-cooper-dKy6K3vfHB8-unsplash.jpg')
Comment.create!(user_id: user2.id, photo_id: px21.id, body: 'Exquisite composition!')
Comment.create!(user_id: user4.id, photo_id: px21.id, body: 'Beautifully done! ')
Comment.create!(user_id: user10.id, photo_id: px21.id, body: 'Stunning capture')
Comment.create!(user_id: user7.id, photo_id: px21.id, body: 'Outstanding work!')
Comment.create!(user_id: user3.id, photo_id: px21.id, body: 'Awesome perspective!')

px22 = Photo.create!(title: 'Fresh', description: 'green plant in tilt shift lens', creator_id: user10.id, unsplashURL: 'https://unsplash.com/photos/ZhkDm071QV4', unsplashUserURL: 'https://unsplash.com/@kekekristen', unsplashName: 'Kristen Colada Adams')
file22 = open('https://perfectpx-seeds.s3.amazonaws.com/kristen-colada-adams-ZhkDm071QV4-unsplash.jpg')
px22.px.attach(io: file22, filename: 'kristen-colada-adams-ZhkDm071QV4-unsplash.jpg')
Comment.create!(user_id: user8.id, photo_id: px22.id, body: 'Everything perfect about the photo.')
Comment.create!(user_id: user7.id, photo_id: px22.id, body: 'Great work')
Comment.create!(user_id: user12.id, photo_id: px22.id, body: 'Very nice shot')
Comment.create!(user_id: user2.id, photo_id: px22.id, body: 'So beautiful')
Comment.create!(user_id: user9.id, photo_id: px22.id, body: 'Wow. Love the energy!')

px23 = Photo.create!(title: 'Earth', description: 'back to basics', creator_id: user11.id, unsplashURL: 'https://unsplash.com/photos/A_p-TL4RS-c', unsplashUserURL: 'https://unsplash.com/@kyle_barr', unsplashName: 'Kyle Barr')
file23 = open('https://perfectpx-seeds.s3.amazonaws.com/kyle-barr-A_p-TL4RS-c-unsplash.jpg')
px23.px.attach(io: file23, filename: 'kyle-barr-A_p-TL4RS-c-unsplash.jpg')
Comment.create!(user_id: user12.id, photo_id: px23.id, body: 'Really stunning capture')
Comment.create!(user_id: user6.id, photo_id: px23.id, body: 'Just perfect')
Comment.create!(user_id: user2.id, photo_id: px23.id, body: 'Very beautiful light and excellent shot')
Comment.create!(user_id: user7.id, photo_id: px23.id, body: 'Nice shot!')
Comment.create!(user_id: user4.id, photo_id: px23.id, body: 'Excellent shot')

px24 = Photo.create!(title: 'Friendly Neighbor', description: 'brown wooden fence with brown curly haired dog', creator_id: user12.id, unsplashURL: 'https://unsplash.com/photos/tErSHe8LmYE', unsplashUserURL: 'https://unsplash.com/@kyle_barr', unsplashName: 'Kyle Barr')
file24 = open('https://perfectpx-seeds.s3.amazonaws.com/kyle-barr-tErSHe8LmYE-unsplash.jpg')
px24.px.attach(io: file24, filename: 'kyle-barr-tErSHe8LmYE-unsplash.jpg')
Comment.create!(user_id: user8.id, photo_id: px24.id, body: 'The colors are so vibrant')
Comment.create!(user_id: user5.id, photo_id: px24.id, body: 'Wonderful shot and tones!')
Comment.create!(user_id: user6.id, photo_id: px24.id, body: 'It''s a beautiful capture')
Comment.create!(user_id: user12.id, photo_id: px24.id, body: 'Excellent work!')
Comment.create!(user_id: user3.id, photo_id: px24.id, body: 'Beautiful image!')

px25 = Photo.create!(title: 'Lilac', description: 'purple and white flower in close up', creator_id: user1.id, unsplashURL: 'https://unsplash.com/photos/FaYpBYUn1cU', unsplashUserURL: 'https://unsplash.com/@lanasly', unsplashName: 'Lana Sly')
file25 = open('https://perfectpx-seeds.s3.amazonaws.com/lana-sly-FaYpBYUn1cU-unsplash.jpg')
px25.px.attach(io: file25, filename: 'lana-sly-FaYpBYUn1cU-unsplash.jpg')
Comment.create!(user_id: user7.id, photo_id: px25.id, body: 'Outstanding')
Comment.create!(user_id: user3.id, photo_id: px25.id, body: 'Beautiful work!')
Comment.create!(user_id: user12.id, photo_id: px25.id, body: 'Excellent shot')
Comment.create!(user_id: user2.id, photo_id: px25.id, body: 'Brilliant shot dear friend')
Comment.create!(user_id: user4.id, photo_id: px25.id, body: 'Impressive photo')

px26 = Photo.create!(title: 'Harvest', description: 'green leaves beside gardening tools', creator_id: user2.id, unsplashURL: 'https://unsplash.com/photos/cUJc1mb3KVg', unsplashUserURL: 'https://unsplash.com/@leighskomal', unsplashName: 'Leigh Skomal')
file26 = open('https://perfectpx-seeds.s3.amazonaws.com/leigh-skomal-cUJc1mb3KVg-unsplash.jpg')
px26.px.attach(io: file26, filename: 'leigh-skomal-cUJc1mb3KVg-unsplash.jpg')
Comment.create!(user_id: user5.id, photo_id: px26.id, body: 'beautiful simplicity..')
Comment.create!(user_id: user8.id, photo_id: px26.id, body: 'Nice!')
Comment.create!(user_id: user11.id, photo_id: px26.id, body: 'Fabulous capture')
Comment.create!(user_id: user9.id, photo_id: px26.id, body: 'Exellent work')
Comment.create!(user_id: user1.id, photo_id: px26.id, body: 'Fantastic atmosphere with soft light!')

px27 = Photo.create!(title: 'Cat', description: 'cat. boots for scale', creator_id: user3.id, unsplashURL: 'https://unsplash.com/photos/cwy90fRMbrQ', unsplashUserURL: 'https://unsplash.com/@yapics', unsplashName: 'Leon Seibert')
file27 = open('https://perfectpx-seeds.s3.amazonaws.com/leon-seibert-cwy90fRMbrQ-unsplash.jpg')
px27.px.attach(io: file27, filename: 'leon-seibert-cwy90fRMbrQ-unsplash.jpg')
Comment.create!(user_id: user11.id, photo_id: px27.id, body: 'Wonderful composition!')
Comment.create!(user_id: user2.id, photo_id: px27.id, body: 'Great lines')
Comment.create!(user_id: user6.id, photo_id: px27.id, body: 'Nice shot')
Comment.create!(user_id: user4.id, photo_id: px27.id, body: 'Stunning work, amazing composition')
Comment.create!(user_id: user8.id, photo_id: px27.id, body: 'Marvelous picture')

px28 = Photo.create!(title: 'Classic', description: 'blue car on road during night', creator_id: user4.id, unsplashURL: 'https://unsplash.com/photos/mAbhy3U14VI', unsplashUserURL: 'https://unsplash.com/@thevantagepoint718', unsplashName: 'Lerone Pieters')
file28 = open('https://perfectpx-seeds.s3.amazonaws.com/lerone-pieters-mAbhy3U14VI-unsplash.jpg')
px28.px.attach(io: file28, filename: 'lerone-pieters-mAbhy3U14VI-unsplash.jpg')
Comment.create!(user_id: user1.id, photo_id: px28.id, body: 'Really fantastic photo.')
Comment.create!(user_id: user10.id, photo_id: px28.id, body: 'Amazing shot! Beautiful colors, light and composition!')
Comment.create!(user_id: user11.id, photo_id: px28.id, body: 'Wooo amazing work so beautiful')
Comment.create!(user_id: user2.id, photo_id: px28.id, body: 'Great mood and compositon!')
Comment.create!(user_id: user7.id, photo_id: px28.id, body: 'Wonderful capture and beautiful mood')

px29 = Photo.create!(title: 'Cake', description: 'for goodness sake, eat some cake', creator_id: user5.id, unsplashURL: 'https://unsplash.com/photos/uS6a4CMv7kc', unsplashUserURL: 'https://unsplash.com/@linaaa3', unsplashName: 'Lina')
file29 = open('https://perfectpx-seeds.s3.amazonaws.com/lina-uS6a4CMv7kc-unsplash.jpg')
px29.px.attach(io: file29, filename: 'lina-uS6a4CMv7kc-unsplash.jpg')
Comment.create!(user_id: user11.id, photo_id: px29.id, body: 'An excellent animal portrait with a very good pose and very pretty colors!')
Comment.create!(user_id: user9.id, photo_id: px29.id, body: 'Beautiful')
Comment.create!(user_id: user10.id, photo_id: px29.id, body: 'An absolutely spectacular image my friend')
Comment.create!(user_id: user4.id, photo_id: px29.id, body: 'Beautiful shot')
Comment.create!(user_id: user2.id, photo_id: px29.id, body: 'Wonderful colours and a fantastic atmosphere.')

px30 = Photo.create!(title: 'rosé', description: 'boxes of wine against the window', creator_id: user6.id, unsplashURL: 'https://unsplash.com/photos/yEH3ZubsZuE', unsplashUserURL: 'https://unsplash.com/@lgnwvr', unsplashName: 'LOGAN WEAVER')
file30 = open('https://perfectpx-seeds.s3.amazonaws.com/logan-weaver-yEH3ZubsZuE-unsplash.jpg')
px30.px.attach(io: file30, filename: 'logan-weaver-yEH3ZubsZuE-unsplash.jpg')
Comment.create!(user_id: user5.id, photo_id: px30.id, body: 'A superb composition, very fine art!')
Comment.create!(user_id: user1.id, photo_id: px30.id, body: 'Excellent, my friend!')
Comment.create!(user_id: user2.id, photo_id: px30.id, body: 'Exceptional.. extraordinary.. magnificent work')
Comment.create!(user_id: user10.id, photo_id: px30.id, body: 'Outstanding work!')
Comment.create!(user_id: user3.id, photo_id: px30.id, body: 'Beautiful composition and mood ')

px31 = Photo.create!(title: 'Cotton Candy', description: 'Beautiful evening sky', creator_id: user7.id, unsplashURL: 'https://unsplash.com/photos/91-z9ZTZyOI', unsplashUserURL: 'https://unsplash.com/@mehadi965', unsplashName: 'Mehadi Hasan')
file31 = open('https://perfectpx-seeds.s3.amazonaws.com/mehadi-hasan-91-z9ZTZyOI-unsplash.jpg')
px31.px.attach(io: file31, filename: 'mehadi-hasan-91-z9ZTZyOI-unsplash.jpg')
Comment.create!(user_id: user2.id, photo_id: px31.id, body: 'What a spectacular image')
Comment.create!(user_id: user9.id, photo_id: px31.id, body: 'congrats on the amazing shot!')
Comment.create!(user_id: user12.id, photo_id: px31.id, body: 'Beautiful jelly fish!')
Comment.create!(user_id: user6.id, photo_id: px31.id, body: 'Amazing capture!')
Comment.create!(user_id: user11.id, photo_id: px31.id, body: 'Lovely work')

px32 = Photo.create!(title: 'Roving', description: 'milky way overhead', creator_id: user8.id, unsplashURL: 'https://unsplash.com/photos/MfH4wQ42nI8', unsplashUserURL: 'https://unsplash.com/@nima_sarram', unsplashName: 'Nima Sarram')
file32 = open('https://perfectpx-seeds.s3.amazonaws.com/nima-sarram-MfH4wQ42nI8-unsplash.jpg')
px32.px.attach(io: file32, filename: 'nima-sarram-MfH4wQ42nI8-unsplash.jpg')
Comment.create!(user_id: user10.id, photo_id: px32.id, body: 'Cute!')
Comment.create!(user_id: user1.id, photo_id: px32.id, body: 'Beautiful light and colour,stunning capture')
Comment.create!(user_id: user4.id, photo_id: px32.id, body: 'Beautifully taken image')
Comment.create!(user_id: user2.id, photo_id: px32.id, body: 'Brilliant.. outstanding work')
Comment.create!(user_id: user6.id, photo_id: px32.id, body: 'marvelous photo')

px33 = Photo.create!(title: 'Fall', description: 'person holding red leaves', creator_id: user9.id, unsplashURL: 'https://unsplash.com/photos/klOPZDHvY4Y', unsplashUserURL: 'https://unsplash.com/@ohhbee', unsplashName: 'Olivia Bauso')
file33 = open('https://perfectpx-seeds.s3.amazonaws.com/olivia-bauso-klOPZDHvY4Y-unsplash.jpg')
px33.px.attach(io: file33, filename: 'olivia-bauso-klOPZDHvY4Y-unsplash.jpg')
Comment.create!(user_id: user2.id, photo_id: px33.id, body: 'Love this one')
Comment.create!(user_id: user4.id, photo_id: px33.id, body: 'Nicely done!')
Comment.create!(user_id: user6.id, photo_id: px33.id, body: 'Excellent perspective')
Comment.create!(user_id: user8.id, photo_id: px33.id, body: 'Fantastic work!')
Comment.create!(user_id: user10.id, photo_id: px33.id, body: 'On top of the world :-)')

px34 = Photo.create!(title: 'Leaf', description: 'green banana leaf in close up', creator_id: user10.id, unsplashURL: 'https://unsplash.com/photos/rFIuhzrYse4', unsplashUserURL: 'https://unsplash.com/@checocanto', unsplashName: 'Osmar do Canto')
file34 = open('https://perfectpx-seeds.s3.amazonaws.com/osmar-do-canto-rFIuhzrYse4-unsplash.jpg')
px34.px.attach(io: file34, filename: 'osmar-do-canto-rFIuhzrYse4-unsplash.jpg')
Comment.create!(user_id: user1.id, photo_id: px34.id, body: 'Wonderful shooting!')
Comment.create!(user_id: user3.id, photo_id: px34.id, body: 'Stunning')
Comment.create!(user_id: user5.id, photo_id: px34.id, body: 'Great angles!')
Comment.create!(user_id: user7.id, photo_id: px34.id, body: 'Wonderful view and amazing capture.​')
Comment.create!(user_id: user9.id, photo_id: px34.id, body: 'Great lighting and colors')

px35 = Photo.create!(title: 'Hocus Pocus', description: 'ready for halloween', creator_id: user11.id, unsplashURL: 'https://unsplash.com/photos/4FmeF_IlYNs', unsplashUserURL: 'https://unsplash.com/@paige_cody', unsplashName: 'Paige Cody')
file35 = open('https://perfectpx-seeds.s3.amazonaws.com/paige-cody-4FmeF_IlYNs-unsplash.jpg')
px35.px.attach(io: file35, filename: 'paige-cody-4FmeF_IlYNs-unsplash.jpg')
Comment.create!(user_id: user12.id, photo_id: px35.id, body: 'Amazing sky and stunning capture​')
Comment.create!(user_id: user10.id, photo_id: px35.id, body: 'It is so good that i cant say anything.')
Comment.create!(user_id: user8.id, photo_id: px35.id, body: 'Interesting moment masterfully captured')
Comment.create!(user_id: user6.id, photo_id: px35.id, body: 'Awesome capture. Fabulous photography')
Comment.create!(user_id: user4.id, photo_id: px35.id, body: 'Wonderful photo and work')

px36 = Photo.create!(title: 'Getting Dark', description: 'silhouette of mountain near body of water during night', creator_id: user12.id, unsplashURL: 'https://unsplash.com/photos/jBW1TaUj_SM', unsplashUserURL: 'https://unsplash.com/@worldsbetweenlines', unsplashName: 'Patrick Hendry')
file36 = open('https://perfectpx-seeds.s3.amazonaws.com/patrick-hendry-jBW1TaUj_SM-unsplash.jpg')
px36.px.attach(io: file36, filename: 'patrick-hendry-jBW1TaUj_SM-unsplash.jpg')
Comment.create!(user_id: user1.id, photo_id: px36.id, body: 'Amazing photo! Beautiful!')
Comment.create!(user_id: user4.id, photo_id: px36.id, body: 'Impressive scenery and atmosphere! Excellent photo!')
Comment.create!(user_id: user7.id, photo_id: px36.id, body: 'Wonderful scenery my friend!')
Comment.create!(user_id: user10.id, photo_id: px36.id, body: 'Incredible atmosphere!')
Comment.create!(user_id: user11.id, photo_id: px36.id, body: 'Beautiful shot, my friend!')

px37 = Photo.create!(title: 'Crooked', description: 'Leaning Tower of Piza', creator_id: user1.id, unsplashURL: 'https://unsplash.com/photos/0UeJa0eVS0o', unsplashUserURL: 'https://unsplash.com/@patrick_schneider', unsplashName: 'Patrick Schneider')
file37 = open('https://perfectpx-seeds.s3.amazonaws.com/patrick-schneider-0UeJa0eVS0o-unsplash.jpg')
px37.px.attach(io: file37, filename: 'patrick-schneider-0UeJa0eVS0o-unsplash.jpg')
Comment.create!(user_id: user2.id, photo_id: px37.id, body: 'Very beautiful photography!')
Comment.create!(user_id: user5.id, photo_id: px37.id, body: 'Fine work!!! Well done')
Comment.create!(user_id: user8.id, photo_id: px37.id, body: 'Very Great photo!')
Comment.create!(user_id: user11.id, photo_id: px37.id, body: 'Stunning capture')
Comment.create!(user_id: user12.id, photo_id: px37.id, body: 'Very Beautiful. Have a nice day my friend.')

px38 = Photo.create!(title: 'Picnic', description: 'food, friends and a picnic blanket', creator_id: user2.id, unsplashURL: 'https://unsplash.com/photos/RRWHQntDk_g', unsplashUserURL: 'https://unsplash.com/@samfernandes', unsplashName: 'Samantha Fernandes')
file38 = open('https://perfectpx-seeds.s3.amazonaws.com/samantha-fernandes-RRWHQntDk_g-unsplash.jpg')
px38.px.attach(io: file38, filename: 'samantha-fernandes-RRWHQntDk_g-unsplash.jpg')
Comment.create!(user_id: user12.id, photo_id: px38.id, body: 'Excellent work')
Comment.create!(user_id: user9.id, photo_id: px38.id, body: 'Wonderful lighting')
Comment.create!(user_id: user6.id, photo_id: px38.id, body: 'So beautiful coloring! Fantastic composition!')
Comment.create!(user_id: user3.id, photo_id: px38.id, body: 'Excellent composition and wonderful color tone!')
Comment.create!(user_id: user1.id, photo_id: px38.id, body: 'Such amazing and cool image')

px39 = Photo.create!(title: 'Autumn', description: 'pumpkin spice everything', creator_id: user3.id, unsplashURL: 'https://unsplash.com/photos/wKFXCOWdcjQ', unsplashUserURL: 'https://unsplash.com/@tipod', unsplashName: 'Sergey Norkov')
file39 = open('https://perfectpx-seeds.s3.amazonaws.com/sergey-norkov-wKFXCOWdcjQ-unsplash.jpg')
px39.px.attach(io: file39, filename: 'sergey-norkov-wKFXCOWdcjQ-unsplash.jpg')
Comment.create!(user_id: user11.id, photo_id: px39.id, body: 'Great angle')
Comment.create!(user_id: user8.id, photo_id: px39.id, body: 'Wonderful lighting')
Comment.create!(user_id: user5.id, photo_id: px39.id, body: 'Brilliant picture')
Comment.create!(user_id: user2.id, photo_id: px39.id, body: 'Sweet work! Well done')
Comment.create!(user_id: user1.id, photo_id: px39.id, body: 'This shot is really fabulous')

px40 = Photo.create!(title: 'Scenic Drive', description: 'overhead shot of car driving on forested road', creator_id: user4.id, unsplashURL: 'https://unsplash.com/photos/5xcaTNbpvK0', unsplashUserURL: 'https://unsplash.com/@house_42', unsplashName: 'Taylor Brandon')
file40 = open('https://perfectpx-seeds.s3.amazonaws.com/taylor-brandon-5xcaTNbpvK0-unsplash.jpg')
px40.px.attach(io: file40, filename: 'taylor-brandon-5xcaTNbpvK0-unsplash.jpg')
Comment.create!(user_id: user1.id, photo_id: px40.id, body: 'Great composition!')
Comment.create!(user_id: user6.id, photo_id: px40.id, body: 'Nice I really like this!')
Comment.create!(user_id: user11.id, photo_id: px40.id, body: 'Lovely and creative.')
Comment.create!(user_id: user5.id, photo_id: px40.id, body: 'Love it fabulous shot')
Comment.create!(user_id: user9.id, photo_id: px40.id, body: 'A great photographer')

px41 = Photo.create!(title: 'Blacked Out', description: 'G500 under the stars', creator_id: user5.id, unsplashURL: 'https://unsplash.com/photos/sMwId7UXDjw', unsplashUserURL: 'https://unsplash.com/@timmeyer', unsplashName: 'Tim Meyer | @timm.jpeg')
file41 = open('https://perfectpx-seeds.s3.amazonaws.com/tim-meyer-timm-jpeg-sMwId7UXDjw-unsplash.jpg')
px41.px.attach(io: file41, filename: 'tim-meyer-timm-jpeg-sMwId7UXDjw-unsplash.jpg')
Comment.create!(user_id: user12.id, photo_id: px41.id, body: 'Beautiful architecture!')
Comment.create!(user_id: user8.id, photo_id: px41.id, body: 'So good')
Comment.create!(user_id: user4.id, photo_id: px41.id, body: 'Amazing shot')
Comment.create!(user_id: user1.id, photo_id: px41.id, body: 'So good')
Comment.create!(user_id: user9.id, photo_id: px41.id, body: 'Beautiful B/W composition work!')

px42 = Photo.create!(title: 'Peak', description: 'Sunset in the dolomites', creator_id: user6.id, unsplashURL: 'https://unsplash.com/photos/W0YS_nFJUmA', unsplashUserURL: 'https://unsplash.com/@tobbes_rd', unsplashName: 'Tobias Rademacher')
file42 = open('https://perfectpx-seeds.s3.amazonaws.com/tobias-rademacher-W0YS_nFJUmA-unsplash.jpg')
px42.px.attach(io: file42, filename: 'tobias-rademacher-W0YS_nFJUmA-unsplash.jpg')
Comment.create!(user_id: user1.id, photo_id: px42.id, body: 'Fantastic portrait with beautiful colors and details!')
Comment.create!(user_id: user10.id, photo_id: px42.id, body: 'Incredible perfection and incredible beauty')
Comment.create!(user_id: user7.id, photo_id: px42.id, body: 'so splendid brilliant and detailed')
Comment.create!(user_id: user4.id, photo_id: px42.id, body: 'Spectacular shot!')
Comment.create!(user_id: user2.id, photo_id: px42.id, body: 'Very beautiful photography')

px43 = Photo.create!(title: 'Going Up', description: 'esclators and stairs to the subway platform', creator_id: user7.id, unsplashURL: 'https://unsplash.com/photos/_2bHXTz3j-E', unsplashUserURL: 'https://unsplash.com/@electerious', unsplashName: 'Tobias Reich')
file43 = open('https://perfectpx-seeds.s3.amazonaws.com/tobias-reich-_2bHXTz3j-E-unsplash.jpg')
px43.px.attach(io: file43, filename: 'tobias-reich-_2bHXTz3j-E-unsplash.jpg')
Comment.create!(user_id: user12.id, photo_id: px43.id, body: 'Marvelous light and pov! Beautiful night scene!')
Comment.create!(user_id: user3.id, photo_id: px43.id, body: 'Brilliant capture')
Comment.create!(user_id: user6.id, photo_id: px43.id, body: 'Phenomenal photography!')
Comment.create!(user_id: user11.id, photo_id: px43.id, body: 'This is awesome. Fabulous shot')
Comment.create!(user_id: user4.id, photo_id: px43.id, body: 'Wow the detailing.. amazing click')

px44 = Photo.create!(title: 'Adventure', description: 'brown wooden bridge in the forest', creator_id: user8.id, unsplashURL: 'https://unsplash.com/photos/nud0QHskxDg', unsplashUserURL: 'https://unsplash.com/@tomaswilliamsa', unsplashName: 'Tomas Williams')
file44 = open('https://perfectpx-seeds.s3.amazonaws.com/tomas-williams-nud0QHskxDg-unsplash.jpg')
px44.px.attach(io: file44, filename: 'tomas-williams-nud0QHskxDg-unsplash.jpg')
Comment.create!(user_id: user6.id, photo_id: px44.id, body: 'So beautiful and elegant portrait!')
Comment.create!(user_id: user9.id, photo_id: px44.id, body: 'Fantastic coloring tone and atmosphere!')
Comment.create!(user_id: user12.id, photo_id: px44.id, body: 'Excellent shot!')
Comment.create!(user_id: user3.id, photo_id: px44.id, body: 'Great work')
Comment.create!(user_id: user5.id, photo_id: px44.id, body: 'Excellent work my friend!')

px45 = Photo.create!(title: 'Green', description: 'green grass in close up', creator_id: user9.id, unsplashURL: 'https://unsplash.com/photos/LwTmzRZmjvE', unsplashUserURL: 'https://unsplash.com/@valentinbvs', unsplashName: 'Valentin BEAUVAIS')
file45 = open('https://perfectpx-seeds.s3.amazonaws.com/valentin-beauvais-LwTmzRZmjvE-unsplash.jpg')
px45.px.attach(io: file45, filename: 'valentin-beauvais-LwTmzRZmjvE-unsplash.jpg')
Comment.create!(user_id: user7.id, photo_id: px45.id, body: 'Incredible photography')
Comment.create!(user_id: user11.id, photo_id: px45.id, body: 'Wonderful atmosphere')
Comment.create!(user_id: user3.id, photo_id: px45.id, body: 'Nice composition! Your pic is amazing!')
Comment.create!(user_id: user5.id, photo_id: px45.id, body: 'Beautiful work')
Comment.create!(user_id: user10.id, photo_id: px45.id, body: 'Excellent composition and wonderful color tone!')

px46 = Photo.create!(title: 'Iceland', description: 'ice on black sand beach', creator_id: user10.id, unsplashURL: 'https://unsplash.com/photos/ZGDpnrHhQsQ', unsplashUserURL: 'https://unsplash.com/@vincentledvina', unsplashName: 'Vincent Ledvina')
file46 = open('https://perfectpx-seeds.s3.amazonaws.com/vincent-ledvina-ZGDpnrHhQsQ-unsplash.jpg')
px46.px.attach(io: file46, filename: 'vincent-ledvina-ZGDpnrHhQsQ-unsplash.jpg')
Comment.create!(user_id: user7.id, photo_id: px46.id, body: 'Simply gorgeous')
Comment.create!(user_id: user8.id, photo_id: px46.id, body: 'Fantastic scenery! Excellent photo!')
Comment.create!(user_id: user9.id, photo_id: px46.id, body: 'Stunning work my friend')
Comment.create!(user_id: user3.id, photo_id: px46.id, body: 'Beautiful!!!')
Comment.create!(user_id: user5.id, photo_id: px46.id, body: 'Outstanding')

px47 = Photo.create!(title: 'Foggy', description: 'fog covered mountains', creator_id: user11.id, unsplashURL: 'https://unsplash.com/photos/DEHNYNoQc8I', unsplashUserURL: 'https://unsplash.com/@myz', unsplashName: 'Yuan Zhe Ma')
file47 = open('https://perfectpx-seeds.s3.amazonaws.com/yuan-zhe-ma-DEHNYNoQc8I-unsplash.jpg')
px47.px.attach(io: file47, filename: 'yuan-zhe-ma-DEHNYNoQc8I-unsplash.jpg')
Comment.create!(user_id: user3.id, photo_id: px47.id, body: 'Wonderful light and view​, amazing capture​')
Comment.create!(user_id: user5.id, photo_id: px47.id, body: 'Wonderful frame, light and colors !')
Comment.create!(user_id: user7.id, photo_id: px47.id, body: 'Great mood')
Comment.create!(user_id: user2.id, photo_id: px47.id, body: 'Excellent work')
Comment.create!(user_id: user9.id, photo_id: px47.id, body: 'Beautiful light and coloring tone!')

px48 = Photo.create!(title: 'Roar', description: 'i\'m a lion, hear me roar!', creator_id: user12.id, unsplashURL: 'https://unsplash.com/photos/0EMQbQQ7JvA', unsplashUserURL: 'https://unsplash.com/@rodreis', unsplashName: 'Rodrigo dos Reis')
file48 = open('https://perfectpx-seeds.s3.amazonaws.com/rodrigo-dos-reis-0EMQbQQ7JvA-unsplash.jpg')
px48.px.attach(io: file48, filename: 'rodrigo-dos-reis-0EMQbQQ7JvA-unsplash.jpg')
Comment.create!(user_id: user4.id, photo_id: px48.id, body: 'Stunning light! Great photo')
Comment.create!(user_id: user2.id, photo_id: px48.id, body: 'Awesome capture')
Comment.create!(user_id: user6.id, photo_id: px48.id, body: 'Fantastic!')
Comment.create!(user_id: user8.id, photo_id: px48.id, body: 'An absolutely powerful image')
Comment.create!(user_id: user10.id, photo_id: px48.id, body: 'Superb work.')
