require 'open-uri'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Photo.destroy_all
Comment.destroy_all
Follow.destroy_all

user1 = User.create!(email: 'doh@mail.com', password: 'hunter2020', username: 'dohmain', fname: 'Joe', lname: 'Doh')
user2 = User.create!(email: 'krapman@mail.com', password: 'hunter2020', username: 'kraPmaN', fname: 'Nam', lname: 'Park')
user3 = User.create!(email: 'neo@matrix', password: 'hunter2020', username: 'Neo', fname: 'Thomas', lname: 'Anderson')
user4 = User.create!(email: 'jules@pulp.com', password: 'hunter2020', username: 'The Shepherd', fname: 'Jules', lname: 'Winnfield')
user5 = User.create!(email: 'kiddo@mail.com', password: 'hunter2020', username: 'The Bride', fname: 'Beatrix', lname: 'Kiddo')
user6 = User.create!(email: 'hpotter@hogs.com', password: 'hunter2020', username: 'Godfather', fname: 'Stan', lname: 'Lee')
user7 = User.create!(email: 'wolverine@xmen.com', password: 'hunter2020', username: 'Wolverine', fname: 'Logan', lname: 'Fowler')
user8 = User.create!(email: 'tony@stark.com', password: 'hunter2020', username: 'Ironman', fname: 'Tony', lname: 'Stark')
user9 = User.create!(email: 'widow@avengers.com', password: 'hunter2020', username: 'Black Widow', fname: 'Natasha', lname: 'Romanova')
user10 = User.create!(email: 'selene@coven.com', password: 'hunter2020', username: 'Death Dealer', fname: 'Selene', lname: 'Corbin')
user11 = User.create!(email: 'kapow@darkhorse.com', password: 'hunter2020', username: 'Wonder Woman', fname: 'Diana', lname: 'Prince')
user12 = User.create!(email: 'demo@demo.com', password: 'hunter2020', username: 'Demolition Man', fname: 'Demo', lname: 'User')

px1 = Photo.create!(title: 'Canadian National Parks playing cards', description: 'white and blue playing cards on brown dried leaves', creator_id: user1.id, unsplashURL: 'https://unsplash.com/photos/kXF5CdmJh88', unsplashUserURL: 'https://unsplash.com/@lureofadventure', unsplashName: 'Ali Kazal')
file1 = open('https://perfectpx-seeds.s3.amazonaws.com/ali-kazal-kXF5CdmJh88-unsplash.jpg')
px1.px.attach(io: file1, filename: 'ali-kazal-kXF5CdmJh88-unsplash.jpg')
Comment.create!(user_id: user2.id, photo_id: px1.id, body: 'awesome picture!')
Comment.create!(user_id: user5.id, photo_id: px1.id, body: 'Marvelous')
Comment.create!(user_id: user7.id, photo_id: px1.id, body: 'Amazing work! Very inspiring')
Comment.create!(user_id: user12.id, photo_id: px1.id, body: 'Stunning capture')
Comment.create!(user_id: user11.id, photo_id: px1.id, body: 'So beautiful nature scenery! Impressive work!')

px2 = Photo.create!(title: 'purrr', description: 'white and brown tabby cat lying on white textile', creator_id: user2.id, unsplashURL: 'https://unsplash.com/photos/jzPbnpoaIHw', unsplashUserURL: 'https://unsplash.com/@alison_wang', unsplashName: 'Alison Wang')
file2 = open('https://perfectpx-seeds.s3.amazonaws.com/alison-wang-jzPbnpoaIHw-unsplash.jpg')
px2.px.attach(io: file2, filename: 'alison-wang-jzPbnpoaIHw-unsplash.jpg')
Comment.create!(user_id: user1.id, photo_id: px2.id, body: 'Excellent photography')
Comment.create!(user_id: user6.id, photo_id: px2.id, body: 'Beautiful shot')
Comment.create!(user_id: user3.id, photo_id: px2.id, body: 'You are doing as wonderful a job')
Comment.create!(user_id: user8.id, photo_id: px2.id, body: 'Absolutely fantastic shot')
Comment.create!(user_id: user10.id, photo_id: px2.id, body: 'very nice photo')

px3 = Photo.create!(title: 'Playing Cards', description: 'person holding playing cards on white table', creator_id: user3.id, unsplashURL: 'https://unsplash.com/photos/S0_Ep9meLFY', unsplashUserURL: 'https://unsplash.com/@andriklangfield', unsplashName: 'Andrik Langfield')
file3 = open('https://perfectpx-seeds.s3.amazonaws.com/andrik-langfield-S0_Ep9meLFY-unsplash.jpg')
px3.px.attach(io: file3, filename: 'andrik-langfield-S0_Ep9meLFY-unsplash.jpg')
Comment.create!(user_id: user4.id, photo_id: px3.id, body: 'That is absolutely sensational')
Comment.create!(user_id: user9.id, photo_id: px3.id, body: 'awesome landscape')
Comment.create!(user_id: user12.id, photo_id: px3.id, body: 'Excellent shot')
Comment.create!(user_id: user7.id, photo_id: px3.id, body: 'Awesome moment')
Comment.create!(user_id: user1.id, photo_id: px3.id, body: 'Wonderful photography')

px4 = Photo.create!(title: 'Fresh Baked', description: 'brown and black pie on black tray', creator_id: user4.id, unsplashURL: 'https://unsplash.com/photos/twni7IlpUDE', unsplashUserURL: 'https://unsplash.com/@anshu18', unsplashName: 'Anshu A')
file4 = open('https://perfectpx-seeds.s3.amazonaws.com/anshu-a-twni7IlpUDE-unsplash.jpg')
px4.px.attach(io: file4, filename: 'anshu-a-twni7IlpUDE-unsplash.jpg')
Comment.create!(user_id: user5.id, photo_id: px4.id, body: 'Fantastic!')
Comment.create!(user_id: user2.id, photo_id: px4.id, body: 'Amazing shot excellent work')
Comment.create!(user_id: user10.id, photo_id: px4.id, body: 'Fantastic light and scenery!')
Comment.create!(user_id: user11.id, photo_id: px4.id, body: 'fantastic photo')
Comment.create!(user_id: user6.id, photo_id: px4.id, body: 'Outstanding work my friend')

px5 = Photo.create!(title: '', description: '', creator_id: user5.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file5 = open('')
px5.px.attach(io: file5, filename: '')
Comment.create!(user_id: user4.id, photo_id: px5.id, body: 'Great and beautiful work!')
Comment.create!(user_id: user8.id, photo_id: px5.id, body: 'Wonderful light and composition')
Comment.create!(user_id: user3.id, photo_id: px5.id, body: 'Fantastic work.')
Comment.create!(user_id: user1.id, photo_id: px5.id, body: 'Gorgeous!')
Comment.create!(user_id: user9.id, photo_id: px5.id, body: 'This is so beautiful!!!')

px6 = Photo.create!(title: '', description: '', creator_id: user6.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file6 = open('')
px6.px.attach(io: file6, filename: '')
Comment.create!(user_id: user12.id, photo_id: px6.id, body: 'Outstanding work!')
Comment.create!(user_id: user3.id, photo_id: px6.id, body: 'Stunning colors and silhouette')
Comment.create!(user_id: user9.id, photo_id: px6.id, body: 'Superb shot loved it.')
Comment.create!(user_id: user10.id, photo_id: px6.id, body: 'Fine photo!!!!')
Comment.create!(user_id: user11.id, photo_id: px6.id, body: 'Excellent shot!')

px7 = Photo.create!(title: '', description: '', creator_id: user7.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file7 = open('')
px7.px.attach(io: file7, filename: '')
Comment.create!(user_id: user2.id, photo_id: px7.id, body: 'Beautifully done!')
Comment.create!(user_id: user8.id, photo_id: px7.id, body: 'Beautiful landscape composition work!')
Comment.create!(user_id: user4.id, photo_id: px7.id, body: 'Fantastic light, mood and composition')
Comment.create!(user_id: user5.id, photo_id: px7.id, body: 'Gorgeous capture, congrats!')
Comment.create!(user_id: user6.id, photo_id: px7.id, body: 'Wowwww!')

px8 = Photo.create!(title: '', description: '', creator_id: user8.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file8 = open('')
px8.px.attach(io: file8, filename: '')
Comment.create!(user_id: user7.id, photo_id: px8.id, body: 'This is lovely')
Comment.create!(user_id: user1.id, photo_id: px8.id, body: 'Bravo!!!')
Comment.create!(user_id: user10.id, photo_id: px8.id, body: 'Wonderful, my friend!')
Comment.create!(user_id: user12.id, photo_id: px8.id, body: 'Your processing is A+')
Comment.create!(user_id: user2.id, photo_id: px8.id, body: 'Wonderfull picture')

px9 = Photo.create!(title: '', description: '', creator_id: user9.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file9 = open('')
px9.px.attach(io: file9, filename: '')
Comment.create!(user_id: user4.id, photo_id: px9.id, body: 'Magnificent landscape work!')
Comment.create!(user_id: user9.id, photo_id: px9.id, body: 'Extraordinary!!')
Comment.create!(user_id: user3.id, photo_id: px9.id, body: 'Wonderful light and view​, amazing capture​')
Comment.create!(user_id: user5.id, photo_id: px9.id, body: 'So beautiful​')
Comment.create!(user_id: user11.id, photo_id: px9.id, body: 'Fantastic capture!')

px10 = Photo.create!(title: '', description: '', creator_id: user10.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file10 = open('')
px10.px.attach(io: file10, filename: '')
Comment.create!(user_id: user6.id, photo_id: px10.id, body: 'Awesome shot, my friend!')
Comment.create!(user_id: user1.id, photo_id: px10.id, body: 'Real masterpiece.')
Comment.create!(user_id: user8.id, photo_id: px10.id, body: 'What an amazing capture!')
Comment.create!(user_id: user11.id, photo_id: px10.id, body: 'Beautiful photo')
Comment.create!(user_id: user3.id, photo_id: px10.id, body: 'Wonderful composition !')

px11 = Photo.create!(title: '', description: '', creator_id: user11.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file11 = open('')
px11.px.attach(io: file11, filename: '')
Comment.create!(user_id: user7.id, photo_id: px11.id, body: 'Tremendous')
Comment.create!(user_id: user12.id, photo_id: px11.id, body: 'Great photo!')
Comment.create!(user_id: user2.id, photo_id: px11.id, body: 'Excellent!')
Comment.create!(user_id: user6.id, photo_id: px11.id, body: 'Terrific work')
Comment.create!(user_id: user5.id, photo_id: px11.id, body: 'Amazing shot')

px12 = Photo.create!(title: '', description: '', creator_id: user12.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file12 = open('')
px12.px.attach(io: file12, filename: '')
Comment.create!(user_id: user4.id, photo_id: px12.id, body: 'Great work, I love the color and light in this photo!')
Comment.create!(user_id: user10.id, photo_id: px12.id, body: 'Spectacular')
Comment.create!(user_id: user7.id, photo_id: px12.id, body: 'Magic')
Comment.create!(user_id: user5.id, photo_id: px12.id, body: 'Very beautiful capture')
Comment.create!(user_id: user1.id, photo_id: px12.id, body: 'Gorgeous shot')

px13 = Photo.create!(title: '', description: '', creator_id: user1.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file13 = open('')
px13.px.attach(io: file13, filename: '')
Comment.create!(user_id: user4.id, photo_id: px13.id, body: 'Wow!! Great image with terrific color, depth, detail and light!')
Comment.create!(user_id: user8.id, photo_id: px13.id, body: 'Striking composition')
Comment.create!(user_id: user12.id, photo_id: px13.id, body: 'Very nicely captured.')
Comment.create!(user_id: user5.id, photo_id: px13.id, body: 'Beautifully done!')
Comment.create!(user_id: user11.id, photo_id: px13.id, body: 'Fabulous image')

px14 = Photo.create!(title: '', description: '', creator_id: user2.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file14 = open('')
px14.px.attach(io: file14, filename: '')
Comment.create!(user_id: user8.id, photo_id: px14.id, body: 'Excellent work')
Comment.create!(user_id: user9.id, photo_id: px14.id, body: 'Great photo.')
Comment.create!(user_id: user3.id, photo_id: px14.id, body: 'I love these layers and colors!')
Comment.create!(user_id: user10.id, photo_id: px14.id, body: 'Very difficult to believe this is natural')
Comment.create!(user_id: user6.id, photo_id: px14.id, body: 'Impressive view and scenery!')

px15 = Photo.create!(title: '', description: '', creator_id: user3.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file15 = open('')
px15.px.attach(io: file15, filename: '')
Comment.create!(user_id: user7.id, photo_id: px15.id, body: 'Beautiful photo')
Comment.create!(user_id: user2.id, photo_id: px15.id, body: 'Beautiful light and colors.')
Comment.create!(user_id: user9.id, photo_id: px15.id, body: 'Outstanding image')
Comment.create!(user_id: user12.id, photo_id: px15.id, body: 'wonderful capture!!!')
Comment.create!(user_id: user4.id, photo_id: px15.id, body: 'Perfect shot')

px16 = Photo.create!(title: '', description: '', creator_id: user4.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file16 = open('')
px16.px.attach(io: file16, filename: '')
Comment.create!(user_id: user9.id, photo_id: px16.id, body: 'Great shot!')
Comment.create!(user_id: user7.id, photo_id: px16.id, body: 'Fabulous capture')
Comment.create!(user_id: user11.id, photo_id: px16.id, body: 'Beautiful colors, this shot is simply excellent!')
Comment.create!(user_id: user1.id, photo_id: px16.id, body: 'Wonderful colors, Perfect light and mood! Very nice!')
Comment.create!(user_id: user3.id, photo_id: px16.id, body: 'Impressive view and scenery!')

px17 = Photo.create!(title: '', description: '', creator_id: user5.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file17 = open('')
px17.px.attach(io: file17, filename: '')
Comment.create!(user_id: user2.id, photo_id: px17.id, body: 'Great timing!')
Comment.create!(user_id: user8.id, photo_id: px17.id, body: 'Outstanding!')
Comment.create!(user_id: user6.id, photo_id: px17.id, body: 'Looks flat to me')
Comment.create!(user_id: user10.id, photo_id: px17.id, body: 'Uncommon view')
Comment.create!(user_id: user1.id, photo_id: px17.id, body: 'Impressive view and scenery!')

px18 = Photo.create!(title: '', description: '', creator_id: user6.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file18 = open('')
px18.px.attach(io: file18, filename: '')
Comment.create!(user_id: user7.id, photo_id: px18.id, body: 'Great comp')
Comment.create!(user_id: user11.id, photo_id: px18.id, body: 'Amazing shot')
Comment.create!(user_id: user5.id, photo_id: px18.id, body: 'Fabulous capture')
Comment.create!(user_id: user2.id, photo_id: px18.id, body: 'Exellent capture and colors.')
Comment.create!(user_id: user3.id, photo_id: px18.id, body: 'Wonderful capture:)')

px19 = Photo.create!(title: '', description: '', creator_id: user7.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file19 = open('')
px19.px.attach(io: file19, filename: '')
Comment.create!(user_id: user4.id, photo_id: px19.id, body: 'Very Beautiful. Have a nice day my friend.')
Comment.create!(user_id: user6.id, photo_id: px19.id, body: 'Beautiful POV and capture')
Comment.create!(user_id: user10.id, photo_id: px19.id, body: 'Truly impressed with your attention catching photograph')
Comment.create!(user_id: user12.id, photo_id: px19.id, body: 'Great scene')
Comment.create!(user_id: user8.id, photo_id: px19.id, body: 'Superb shot')

px20 = Photo.create!(title: '', description: '', creator_id: user8.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file20 = open('')
px20.px.attach(io: file20, filename: '')
Comment.create!(user_id: user9.id, photo_id: px20.id, body: 'Magnificent picture excellent work')
Comment.create!(user_id: user3.id, photo_id: px20.id, body: 'Magnificent photo!')
Comment.create!(user_id: user11.id, photo_id: px20.id, body: 'Wonderful light and view​, amazing capture​')
Comment.create!(user_id: user5.id, photo_id: px20.id, body: 'Great shot, beautiful edit')
Comment.create!(user_id: user1.id, photo_id: px20.id, body: 'Excellent shot')

px21 = Photo.create!(title: '', description: '', creator_id: user9.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file21 = open('')
px21.px.attach(io: file21, filename: '')
Comment.create!(user_id: user2.id, photo_id: px21.id, body: 'Exquisite composition!')
Comment.create!(user_id: user4.id, photo_id: px21.id, body: 'Beautifully done! ')
Comment.create!(user_id: user10.id, photo_id: px21.id, body: 'Stunning capture')
Comment.create!(user_id: user7.id, photo_id: px21.id, body: 'Outstanding work!')
Comment.create!(user_id: user3.id, photo_id: px21.id, body: 'Awesome perspective!')

px22 = Photo.create!(title: '', description: '', creator_id: user10.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file22 = open('')
px22.px.attach(io: file22, filename: '')
Comment.create!(user_id: user8.id, photo_id: px22.id, body: 'Everything perfect about the photo.')
Comment.create!(user_id: user7.id, photo_id: px22.id, body: 'Great work')
Comment.create!(user_id: user12.id, photo_id: px22.id, body: 'Very nice shot')
Comment.create!(user_id: user2.id, photo_id: px22.id, body: 'So beautiful')
Comment.create!(user_id: user9.id, photo_id: px22.id, body: 'Wow. Love the energy!')

px23 = Photo.create!(title: '', description: '', creator_id: user11.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file23 = open('')
px23.px.attach(io: file23, filename: '')
Comment.create!(user_id: user12.id, photo_id: px23.id, body: 'Really stunning capture')
Comment.create!(user_id: user6.id, photo_id: px23.id, body: 'Just perfect')
Comment.create!(user_id: user2.id, photo_id: px23.id, body: 'Very beautiful light and excellent shot')
Comment.create!(user_id: user7.id, photo_id: px23.id, body: 'Nice shot!')
Comment.create!(user_id: user4.id, photo_id: px23.id, body: 'Excellent shot')

px24 = Photo.create!(title: '', description: '', creator_id: user12.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file24 = open('')
px24.px.attach(io: file24, filename: '')
Comment.create!(user_id: user8.id, photo_id: px24.id, body: 'The colors are so vibrant')
Comment.create!(user_id: user5.id, photo_id: px24.id, body: 'Wonderful shot and tones!')
Comment.create!(user_id: user6.id, photo_id: px24.id, body: 'It''s a beautiful capture')
Comment.create!(user_id: user12.id, photo_id: px24.id, body: 'Excellent work!')
Comment.create!(user_id: user3.id, photo_id: px24.id, body: 'Beautiful image!')

px25 = Photo.create!(title: '', description: '', creator_id: user1.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file25 = open('')
px25.px.attach(io: file25, filename: '')
Comment.create!(user_id: user7.id, photo_id: px25.id, body: 'Outstanding')
Comment.create!(user_id: user3.id, photo_id: px25.id, body: 'Beautiful work!')
Comment.create!(user_id: user12.id, photo_id: px25.id, body: 'Excellent shot')
Comment.create!(user_id: user2.id, photo_id: px25.id, body: 'Brilliant shot dear friend')
Comment.create!(user_id: user4.id, photo_id: px25.id, body: 'Impressive photo')

px26 = Photo.create!(title: '', description: '', creator_id: user2.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file26 = open('')
px26.px.attach(io: file26, filename: '')
Comment.create!(user_id: user5.id, photo_id: px26.id, body: 'beautiful simplicity..')
Comment.create!(user_id: user8.id, photo_id: px26.id, body: 'Nice!')
Comment.create!(user_id: user11.id, photo_id: px26.id, body: 'Fabulous capture')
Comment.create!(user_id: user9.id, photo_id: px26.id, body: 'Exellent work')
Comment.create!(user_id: user1.id, photo_id: px26.id, body: 'Fantastic atmosphere with soft light!')

px27 = Photo.create!(title: '', description: '', creator_id: user3.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file27 = open('')
px27.px.attach(io: file27, filename: '')
Comment.create!(user_id: user11.id, photo_id: px27.id, body: 'Wonderful composition!')
Comment.create!(user_id: user2.id, photo_id: px27.id, body: 'Great lines')
Comment.create!(user_id: user6.id, photo_id: px27.id, body: 'Nice shot')
Comment.create!(user_id: user4.id, photo_id: px27.id, body: 'Stunning work, amazing composition')
Comment.create!(user_id: user8.id, photo_id: px27.id, body: 'Marvelous picture')

px28 = Photo.create!(title: '', description: '', creator_id: user4.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file28 = open('')
px28.px.attach(io: file28, filename: '')
Comment.create!(user_id: user1.id, photo_id: px28.id, body: 'Really fantastic photo.')
Comment.create!(user_id: user10.id, photo_id: px28.id, body: 'Amazing shot! Beautiful colors, light and composition!')
Comment.create!(user_id: user11.id, photo_id: px28.id, body: 'Wooo amazing work so beautiful')
Comment.create!(user_id: user2.id, photo_id: px28.id, body: 'Great mood and compositon!')
Comment.create!(user_id: user7.id, photo_id: px28.id, body: 'Wonderful capture and beautiful mood')

px29 = Photo.create!(title: '', description: '', creator_id: user5.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file29 = open('')
px29.px.attach(io: file29, filename: 'young_moo.jpg')
Comment.create!(user_id: user11.id, photo_id: px29.id, body: 'An excellent animal portrait with a very good pose and very pretty colors!')
Comment.create!(user_id: user9.id, photo_id: px29.id, body: 'Beautiful')
Comment.create!(user_id: user10.id, photo_id: px29.id, body: 'An absolutely spectacular image my friend')
Comment.create!(user_id: user4.id, photo_id: px29.id, body: 'Beautiful shot')
Comment.create!(user_id: user2.id, photo_id: px29.id, body: 'Wonderful colours and a fantastic atmosphere.')

px30 = Photo.create!(title: '', description: '', creator_id: user6.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file30 = open('')
px30.px.attach(io: file30, filename: '')
Comment.create!(user_id: user5.id, photo_id: px30.id, body: 'A superb composition, very fine art!')
Comment.create!(user_id: user1.id, photo_id: px30.id, body: 'Excellent, my friend!')
Comment.create!(user_id: user2.id, photo_id: px30.id, body: 'Exceptional.. extraordinary.. magnificent work')
Comment.create!(user_id: user10.id, photo_id: px30.id, body: 'Outstanding work!')
Comment.create!(user_id: user3.id, photo_id: px30.id, body: 'Beautiful composition and mood ')

px31 = Photo.create!(title: '', description: '', creator_id: user7.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file31 = open('')
px31.px.attach(io: file31, filename: '')
Comment.create!(user_id: user2.id, photo_id: px31.id, body: 'What a spectacular image')
Comment.create!(user_id: user9.id, photo_id: px31.id, body: 'congrats on the amazing shot!')
Comment.create!(user_id: user12.id, photo_id: px31.id, body: 'Beautiful jelly fish!')
Comment.create!(user_id: user6.id, photo_id: px31.id, body: 'Amazing capture!')
Comment.create!(user_id: user11.id, photo_id: px31.id, body: 'Lovely work')

px32 = Photo.create!(title: '', description: '', creator_id: user8.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file32 = open('')
px32.px.attach(io: file32, filename: '')
Comment.create!(user_id: user10.id, photo_id: px32.id, body: 'Cute!')
Comment.create!(user_id: user1.id, photo_id: px32.id, body: 'Beautiful light and colour,stunning capture')
Comment.create!(user_id: user4.id, photo_id: px32.id, body: 'Beautifully taken image')
Comment.create!(user_id: user2.id, photo_id: px32.id, body: 'Brilliant.. outstanding work')
Comment.create!(user_id: user6.id, photo_id: px32.id, body: 'marvelous photo')

px33 = Photo.create!(title: '', description: '', creator_id: user9.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file33 = open('')
px33.px.attach(io: file33, filename: '')
Comment.create!(user_id: user2.id, photo_id: px33.id, body: 'Love this one')
Comment.create!(user_id: user4.id, photo_id: px33.id, body: 'Nicely done!')
Comment.create!(user_id: user6.id, photo_id: px33.id, body: 'Excellent perspective')
Comment.create!(user_id: user8.id, photo_id: px33.id, body: 'Fantastic work!')
Comment.create!(user_id: user10.id, photo_id: px33.id, body: 'On top of the world :-)')

px34 = Photo.create!(title: '', description: '', creator_id: user10.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file34 = open('')
px34.px.attach(io: file34, filename: '')
Comment.create!(user_id: user1.id, photo_id: px34.id, body: 'Wonderful shooting!')
Comment.create!(user_id: user3.id, photo_id: px34.id, body: 'Stunning')
Comment.create!(user_id: user5.id, photo_id: px34.id, body: 'Great angles!')
Comment.create!(user_id: user7.id, photo_id: px34.id, body: 'Wonderful view and amazing capture.​')
Comment.create!(user_id: user9.id, photo_id: px34.id, body: 'Great lighting and colors')

px35 = Photo.create!(title: '', description: '', creator_id: user11.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file35 = open('')
px35.px.attach(io: file35, filename: '')
Comment.create!(user_id: user12.id, photo_id: px35.id, body: 'Amazing sky and stunning capture​')
Comment.create!(user_id: user10.id, photo_id: px35.id, body: 'It is so good that i cant say anything.')
Comment.create!(user_id: user8.id, photo_id: px35.id, body: 'Interesting moment masterfully captured')
Comment.create!(user_id: user6.id, photo_id: px35.id, body: 'Awesome capture. Fabulous photography')
Comment.create!(user_id: user4.id, photo_id: px35.id, body: 'Wonderful photo and work')

px36 = Photo.create!(title: '', description: '', creator_id: user12.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file36 = open('')
px36.px.attach(io: file36, filename: '')
Comment.create!(user_id: user1.id, photo_id: px36.id, body: 'Amazing photo! Beautiful!')
Comment.create!(user_id: user4.id, photo_id: px36.id, body: 'Impressive scenery and atmosphere! Excellent photo!')
Comment.create!(user_id: user7.id, photo_id: px36.id, body: 'Wonderful scenery my friend!')
Comment.create!(user_id: user10.id, photo_id: px36.id, body: 'Incredible atmosphere!')
Comment.create!(user_id: user11.id, photo_id: px36.id, body: 'Beautiful shot, my friend!')

px37 = Photo.create!(title: '', description: '', creator_id: user1.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file37 = open('')
px37.px.attach(io: file37, filename: '')
Comment.create!(user_id: user2.id, photo_id: px37.id, body: 'Very beautiful photography!')
Comment.create!(user_id: user5.id, photo_id: px37.id, body: 'Fine work!!! Well done')
Comment.create!(user_id: user8.id, photo_id: px37.id, body: 'Very Great photo!')
Comment.create!(user_id: user11.id, photo_id: px37.id, body: 'Stunning capture')
Comment.create!(user_id: user12.id, photo_id: px37.id, body: 'Very Beautiful. Have a nice day my friend.')

px38 = Photo.create!(title: '', description: '', creator_id: user2.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file38 = open('')
px38.px.attach(io: file38, filename: '')
Comment.create!(user_id: user12.id, photo_id: px38.id, body: 'Excellent work')
Comment.create!(user_id: user9.id, photo_id: px38.id, body: 'Wonderful lighting')
Comment.create!(user_id: user6.id, photo_id: px38.id, body: 'So beautiful coloring! Fantastic composition!')
Comment.create!(user_id: user3.id, photo_id: px38.id, body: 'Excellent composition and wonderful color tone!')
Comment.create!(user_id: user1.id, photo_id: px38.id, body: 'Such amazing and cool image')

px39 = Photo.create!(title: '', description: '', creator_id: user3.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file39 = open('')
px39.px.attach(io: file39, filename: '')
Comment.create!(user_id: user11.id, photo_id: px39.id, body: 'Great angle')
Comment.create!(user_id: user8.id, photo_id: px39.id, body: 'Wonderful lighting')
Comment.create!(user_id: user5.id, photo_id: px39.id, body: 'Brilliant picture')
Comment.create!(user_id: user2.id, photo_id: px39.id, body: 'Sweet work! Well done')
Comment.create!(user_id: user1.id, photo_id: px39.id, body: 'This shot is really fabulous')

px40 = Photo.create!(title: '', description: '', creator_id: user4.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file40 = open('')
px40.px.attach(io: file40, filename: '')
Comment.create!(user_id: user1.id, photo_id: px40.id, body: 'Great composition!')
Comment.create!(user_id: user6.id, photo_id: px40.id, body: 'Nice I really like this!')
Comment.create!(user_id: user11.id, photo_id: px40.id, body: 'Lovely and creative.')
Comment.create!(user_id: user5.id, photo_id: px40.id, body: 'Love it fabulous shot')
Comment.create!(user_id: user9.id, photo_id: px40.id, body: 'A great photographer')

px41 = Photo.create!(title: '', description: '', creator_id: user5.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file41 = open('')
px41.px.attach(io: file41, filename: '')
Comment.create!(user_id: user12.id, photo_id: px41.id, body: 'Beautiful architecture!')
Comment.create!(user_id: user8.id, photo_id: px41.id, body: 'So good')
Comment.create!(user_id: user4.id, photo_id: px41.id, body: 'Amazing shot')
Comment.create!(user_id: user1.id, photo_id: px41.id, body: 'So good')
Comment.create!(user_id: user9.id, photo_id: px41.id, body: 'Beautiful B/W composition work!')

px42 = Photo.create!(title: '', description: '', creator_id: user6.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file42 = open('')
px42.px.attach(io: file42, filename: '')
Comment.create!(user_id: user1.id, photo_id: px42.id, body: 'Fantastic portrait with beautiful colors and details!')
Comment.create!(user_id: user10.id, photo_id: px42.id, body: 'Incredible perfection and incredible beauty')
Comment.create!(user_id: user7.id, photo_id: px42.id, body: 'so splendid brilliant and detailed')
Comment.create!(user_id: user4.id, photo_id: px42.id, body: 'Spectacular shot!')
Comment.create!(user_id: user2.id, photo_id: px42.id, body: 'Very beautiful photography')

px43 = Photo.create!(title: '', description: '', creator_id: user7.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file43 = open('')
px43.px.attach(io: file43, filename: '')
Comment.create!(user_id: user12.id, photo_id: px43.id, body: 'Marvelous light and pov! Beautiful night scene!')
Comment.create!(user_id: user3.id, photo_id: px43.id, body: 'Brilliant capture')
Comment.create!(user_id: user6.id, photo_id: px43.id, body: 'Phenomenal photography!')
Comment.create!(user_id: user11.id, photo_id: px43.id, body: 'This is awesome. Fabulous shot')
Comment.create!(user_id: user4.id, photo_id: px43.id, body: 'Wow the detailing.. amazing click')

px44 = Photo.create!(title: '', description: '', creator_id: user8.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file44 = open('')
px44.px.attach(io: file44, filename: '')
Comment.create!(user_id: user6.id, photo_id: px44.id, body: 'So beautiful and elegant portrait!')
Comment.create!(user_id: user9.id, photo_id: px44.id, body: 'Fantastic coloring tone and atmosphere!')
Comment.create!(user_id: user12.id, photo_id: px44.id, body: 'Excellent shot!')
Comment.create!(user_id: user3.id, photo_id: px44.id, body: 'Great work')
Comment.create!(user_id: user5.id, photo_id: px44.id, body: 'Excellent work my friend!')

px45 = Photo.create!(title: '', description: '', creator_id: user9.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file45 = open('')
px45.px.attach(io: file45, filename: '')
Comment.create!(user_id: user7.id, photo_id: px45.id, body: 'Incredible photography')
Comment.create!(user_id: user11.id, photo_id: px45.id, body: 'Wonderful atmosphere')
Comment.create!(user_id: user3.id, photo_id: px45.id, body: 'Nice composition! Your pic is amazing!')
Comment.create!(user_id: user5.id, photo_id: px45.id, body: 'Beautiful work')
Comment.create!(user_id: user10.id, photo_id: px45.id, body: 'Excellent composition and wonderful color tone!')

px46 = Photo.create!(title: '', description: '', creator_id: user10.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file46 = open('')
px46.px.attach(io: file46, filename: '')
Comment.create!(user_id: user7.id, photo_id: px46.id, body: 'Simply gorgeous')
Comment.create!(user_id: user8.id, photo_id: px46.id, body: 'Fantastic scenery! Excellent photo!')
Comment.create!(user_id: user9.id, photo_id: px46.id, body: 'Stunning work my friend')
Comment.create!(user_id: user3.id, photo_id: px46.id, body: 'Beautiful!!!')
Comment.create!(user_id: user5.id, photo_id: px46.id, body: 'Outstanding')

px47 = Photo.create!(title: '', description: '', creator_id: user11.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file47 = open('')
px47.px.attach(io: file47, filename: '')
Comment.create!(user_id: user3.id, photo_id: px47.id, body: 'Wonderful light and view​, amazing capture​')
Comment.create!(user_id: user5.id, photo_id: px47.id, body: 'Wonderful frame, light and colors !')
Comment.create!(user_id: user7.id, photo_id: px47.id, body: 'Great mood')
Comment.create!(user_id: user2.id, photo_id: px47.id, body: 'Excellent work')
Comment.create!(user_id: user9.id, photo_id: px47.id, body: 'Beautiful light and coloring tone!')

px48 = Photo.create!(title: '', description: '', creator_id: user12.id, unsplashURL: '', unsplashUserURL: '', unsplashName: '')
file48 = open('')
px48.px.attach(io: file48, filename: '')
Comment.create!(user_id: user4.id, photo_id: px48.id, body: 'Stunning light! Great photo')
Comment.create!(user_id: user2.id, photo_id: px48.id, body: 'Awesome capture')
Comment.create!(user_id: user6.id, photo_id: px48.id, body: 'Fantastic!')
Comment.create!(user_id: user8.id, photo_id: px48.id, body: 'An absolutely powerful image')
Comment.create!(user_id: user10.id, photo_id: px48.id, body: 'Superb work.')
