require 'open-uri'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Photo.destroy_all
Comment.destroy_all

user1 = User.create!(email: 'doh@mail.com', password: 'hunter2020', username: 'doh', fname: 'Joe', lname: 'Doh')
user2 = User.create!(email: 'krapman@mail.com', password: 'hunter2020', username: 'kraPmaN', fname: 'Nam', lname: 'Park')
user3 = User.create!(email: 'neo@matrix', password: 'hunter2020', username: 'Neo', fname: 'Thomas', lname: 'Anderson')
user4 = User.create!(email: 'jules@pulp.com', password: 'hunter2020', username: 'The Shepherd', fname: 'Jules', lname: 'Winnfield')
user5 = User.create!(email: 'kiddo@mail.com', password: 'hunter2020', username: 'The Bride', fname: 'Beatrix', lname: 'kiddo')
user6 = User.create!(email: 'hpotter@hogs.com', password: 'hunter2020', username: 'HPotter', fname: 'Harry', lname: 'Potter')
user7 = User.create!(email: 'wolverine@xmen.com', password: 'hunter2020', username: 'Wolverine', fname: 'Logan', lname: 'Fowler')
user8 = User.create!(email: 'tony@stark.com', password: 'hunter2020', username: 'Ironman', fname: 'Tony', lname: 'Stark')
user9 = User.create!(email: 'widow@avengers.com', password: 'hunter2020', username: 'Black Widow', fname: 'Natasha', lname: 'Romanova')
user10 = User.create!(email: 'selene@coven.com', password: 'hunter2020', username: 'Selene', fname: 'Selene', lname: 'Corbin')
user11 = User.create!(email: 'kapow@bayside.edu', password: 'hunter2020', username: 'kapow', fname: 'Kelly', lname: 'Kapowski')
user12 = User.create!(email: 'demo@demo.com', password: 'hunter2020', username: 'Demo User', fname: 'Demo', lname: 'User')

px1 = Photo.create!(title: 'Snowy Mountain', description: 'Snow covered mountain in front of stars', creator_id: user1.id)
file1 = open('https://perfectpx-seeds.s3.amazonaws.com/black_white_mountain.jpg')
px1.px.attach(io: file1, filename: 'black_white_mountain.jpg')
comment1 = Comment.create!(user_id: user2.id, photo_id: px1.id, body: 'awesome picture!')
comment2 = Comment.create!(user_id: user5.id, photo_id: px1.id, body: 'Marvelous')
comment3 = Comment.create!(user_id: user7.id, photo_id: px1.id, body: 'Amazing work! Very inspiring')
comment4 = Comment.create!(user_id: user12.id, photo_id: px1.id, body: 'Stunning capture')
comment5 = Comment.create!(user_id: user11.id, photo_id: px1.id, body: 'So beautiful nature scenery! Impressive work!')

px2 = Photo.create!(title: 'Littlefinger Beach', description: 'Aerial view of littlefinger beach', creator_id: user2.id)
file2 = open('https://perfectpx-seeds.s3.amazonaws.com/littlefinger_beach.jpg')
px2.px.attach(io: file2, filename: 'littlefinger_beach.jpg')
comment6 = Comment.create!(user_id: user1.id, photo_id: px2.id, body: 'Excellent photography')
comment7 = Comment.create!(user_id: user6.id, photo_id: px2.id, body: 'Beautiful shot')
comment8 = Comment.create!(user_id: user3.id, photo_id: px2.id, body: 'You are doing as wonderful a job')
comment9 = Comment.create!(user_id: user8.id, photo_id: px2.id, body: 'Absolutely fantastic shot')
comment10 = Comment.create!(user_id: user10.id, photo_id: px2.id, body: 'very nice photo')

px3 = Photo.create!(title: 'Hot Air Balloons', description: 'Two hot air balloons floating', creator_id: user3.id)
file3 = open('https://perfectpx-seeds.s3.amazonaws.com/hot_air_balloons.jpg')
px3.px.attach(io: file3, filename: 'hot_air_balloons.jpg')
comment11 = Comment.create!(user_id: user4.id, photo_id: px3.id, body: 'That is absolutely sensational')
comment12 = Comment.create!(user_id: user9.id, photo_id: px3.id, body: 'awesome landscape')
comment13 = Comment.create!(user_id: user12.id, photo_id: px3.id, body: 'Excellent shot')
comment14 = Comment.create!(user_id: user7.id, photo_id: px3.id, body: 'Awesome moment')
comment15 = Comment.create!(user_id: user1.id, photo_id: px3.id, body: 'Wonderful photography')

px4 = Photo.create!(title: 'Moonlight', description: 'Moon over mountain silhouette', creator_id: user4.id)
file4 = open('https://perfectpx-seeds.s3.amazonaws.com/moon_mountains.jpg')
px4.px.attach(io: file4, filename: 'moon_mountains.jpg')
comment16 = Comment.create!(user_id: user5.id, photo_id: px4.id, body: 'Fantastic!')
comment17 = Comment.create!(user_id: user2.id, photo_id: px4.id, body: 'Amazing shot excellent work')
comment18 = Comment.create!(user_id: user10.id, photo_id: px4.id, body: 'Fantastic light and scenery!')
comment19 = Comment.create!(user_id: user11.id, photo_id: px4.id, body: 'fantastic photo')
comment20 = Comment.create!(user_id: user6.id, photo_id: px4.id, body: 'Outstanding work my friend')

px5 = Photo.create!(title: 'Miami', description: 'Sunset and palm trees', creator_id: user5.id)
file5 = open('https://perfectpx-seeds.s3.amazonaws.com/palmtree_sunset.jpg')
px5.px.attach(io: file5, filename: 'palmtree_sunset.jpg')
comment21 = Comment.create!(user_id: user4.id, photo_id: px5.id, body: 'Great and beautiful work!')
comment22 = Comment.create!(user_id: user8.id, photo_id: px5.id, body: 'Wonderful light and composition')
comment23 = Comment.create!(user_id: user3.id, photo_id: px5.id, body: 'Fantastic work.')
comment24 = Comment.create!(user_id: user1.id, photo_id: px5.id, body: 'Gorgeous!')
comment25 = Comment.create!(user_id: user9.id, photo_id: px5.id, body: 'This is so beautiful!!!')

px6 = Photo.create!(title: 'Swiss Mountains', description: 'Snow-capped mountains of Switzerland', creator_id: user6.id)
file6 = open('https://perfectpx-seeds.s3.amazonaws.com/swiss_mountains.jpg')
px6.px.attach(io: file6, filename: 'swiss_mountains.jpg')
comment26 = Comment.create!(user_id: user12.id, photo_id: px6.id, body: 'Outstanding work!')
comment27 = Comment.create!(user_id: user3.id, photo_id: px6.id, body: 'Stunning colors and silhouette')
comment28 = Comment.create!(user_id: user9.id, photo_id: px6.id, body: 'Superb shot loved it.')
comment29 = Comment.create!(user_id: user10.id, photo_id: px6.id, body: 'Fine photo!!!!')
comment30 = Comment.create!(user_id: user11.id, photo_id: px6.id, body: 'Excellent shot!')

px7 = Photo.create!(title: 'Offroading', description: 'SUV driving over water', creator_id: user7.id)
file7 = open('https://perfectpx-seeds.s3.amazonaws.com/suv_on_water.jpg')
px7.px.attach(io: file7, filename: 'suv_on_water.jpg')
comment31 = Comment.create!(user_id: user2.id, photo_id: px7.id, body: 'Beautifully done!')
comment32 = Comment.create!(user_id: user8.id, photo_id: px7.id, body: 'Beautiful landscape composition work!')
comment33 = Comment.create!(user_id: user4.id, photo_id: px7.id, body: 'Fantastic light, mood and composition')
comment34 = Comment.create!(user_id: user5.id, photo_id: px7.id, body: 'Gorgeous capture, congrats!')
comment35 = Comment.create!(user_id: user6.id, photo_id: px7.id, body: 'Wowwww!')

px8 = Photo.create!(title: 'Lakeside', description: 'Couple of old lakeside houses', creator_id: user8.id)
file8 = open('https://perfectpx-seeds.s3.amazonaws.com/lakeside_houses.jpg')
px8.px.attach(io: file8, filename: 'lakeside_houses.jpg')
comment36 = Comment.create!(user_id: user7.id, photo_id: px8.id, body: 'This is lovely')
comment37 = Comment.create!(user_id: user1.id, photo_id: px8.id, body: 'Bravo!!!')
comment38 = Comment.create!(user_id: user10.id, photo_id: px8.id, body: 'Wonderful, my friend!')
comment39 = Comment.create!(user_id: user12.id, photo_id: px8.id, body: 'Your processing is A+')
comment40 = Comment.create!(user_id: user2.id, photo_id: px8.id, body: 'Wonderfull picture')

px9 = Photo.create!(title: 'Bali Beach', description: 'Aerial shot of a beach in Bali', creator_id: user9.id)
file9 = open('https://perfectpx-seeds.s3.amazonaws.com/bali_aerial_shot.jpg')
px9.px.attach(io: file9, filename: 'bali_aerial_shot.jpg')
comment41 = Comment.create!(user_id: user4.id, photo_id: px9.id, body: 'Magnificent landscape work!')
comment42 = Comment.create!(user_id: user9.id, photo_id: px9.id, body: 'Extraordinary!!')
comment43 = Comment.create!(user_id: user3.id, photo_id: px9.id, body: 'Wonderful light and view​, amazing capture​')
comment44 = Comment.create!(user_id: user5.id, photo_id: px9.id, body: 'So beautiful​')
comment45 = Comment.create!(user_id: user11.id, photo_id: px9.id, body: 'Fantastic capture!')

px10 = Photo.create!(title: 'Denmark National Aquarium', description: 'Entrance way to the Denmark National Aquarium', creator_id: user10.id)
file10 = open('https://perfectpx-seeds.s3.amazonaws.com/denmark_national_aquarium.jpg')
px10.px.attach(io: file10, filename: 'denmark_national_aquarium.jpg')
comment46 = Comment.create!(user_id: user6.id, photo_id: px10.id, body: 'Awesome shot, my friend!')
comment47 = Comment.create!(user_id: user1.id, photo_id: px10.id, body: 'Real masterpiece.')
comment48 = Comment.create!(user_id: user8.id, photo_id: px10.id, body: 'What an amazing capture!')
comment49 = Comment.create!(user_id: user11.id, photo_id: px10.id, body: 'Beautiful photo')
comment50 = Comment.create!(user_id: user3.id, photo_id: px10.id, body: 'Wonderful composition !')

px11 = Photo.create!(title: 'Skyscrapers', description: 'Skyscrapers in the Toronto financial district', creator_id: user11.id)
file11 = open('https://perfectpx-seeds.s3.amazonaws.com/toronto_skyscrapers.jpg')
px11.px.attach(io: file11, filename: 'toronto_skyscrapers.jpg')
comment51 = Comment.create!(user_id: user7.id, photo_id: px11.id, body: 'Tremendous')
comment52 = Comment.create!(user_id: user12.id, photo_id: px11.id, body: 'Great photo!')
comment53 = Comment.create!(user_id: user2.id, photo_id: px11.id, body: 'Excellent!')
comment54 = Comment.create!(user_id: user6.id, photo_id: px11.id, body: 'Terrific work')
comment55 = Comment.create!(user_id: user5.id, photo_id: px11.id, body: 'Amazing shot')

px12 = Photo.create!(title: 'Summer Palm Trees', description: 'Green Palm Trees from below', creator_id: user12.id)
file12 = open('https://perfectpx-seeds.s3.amazonaws.com/green_palmtree.jpg')
px12.px.attach(io: file12, filename: 'green_palmtree.jpg')
comment56 = Comment.create!(user_id: user4.id, photo_id: px12.id, body: 'Great work, I love the color and light in this photo!')
comment57 = Comment.create!(user_id: user10.id, photo_id: px12.id, body: 'Spectacular')
comment58 = Comment.create!(user_id: user7.id, photo_id: px12.id, body: 'Magic')
comment59 = Comment.create!(user_id: user5.id, photo_id: px12.id, body: 'Very beautiful capture')
comment60 = Comment.create!(user_id: user1.id, photo_id: px12.id, body: 'Gorgeous shot')

px13 = Photo.create!(title: 'Vintage Ride', description: 'Red leather interior of vintage car', creator_id: user1.id)
file13 = open('https://perfectpx-seeds.s3.amazonaws.com/vintage_red_interior.jpg')
px13.px.attach(io: file13, filename: 'vintage_red_interior.jpg')
comment61 = Comment.create!(user_id: user4.id, photo_id: px13.id, body: 'Wow!! Great image with terrific color, depth, detail and light!')
comment62 = Comment.create!(user_id: user8.id, photo_id: px13.id, body: 'Striking composition')
comment63 = Comment.create!(user_id: user12.id, photo_id: px13.id, body: 'Very nicely captured.')
comment64 = Comment.create!(user_id: user5.id, photo_id: px13.id, body: 'Beautifully done!')
comment65 = Comment.create!(user_id: user11.id, photo_id: px13.id, body: 'Fabulous image')

px14 = Photo.create!(title: 'Prairie House', description: 'Prairie house on slanted hillside', creator_id: user2.id)
file14 = open('https://perfectpx-seeds.s3.amazonaws.com/hillside_house.jpg')
px14.px.attach(io: file14, filename: 'hillside_house.jpg')
comment66 = Comment.create!(user_id: user8.id, photo_id: px14.id, body: 'Excellent work')
comment67 = Comment.create!(user_id: user9.id, photo_id: px14.id, body: 'Great photo.')
comment68 = Comment.create!(user_id: user3.id, photo_id: px14.id, body: 'I love these layers and colors!')
comment69 = Comment.create!(user_id: user10.id, photo_id: px14.id, body: 'Very difficult to believe this is natural')
comment70 = Comment.create!(user_id: user6.id, photo_id: px14.id, body: 'Impressive view and scenery!')

px15 = Photo.create!(title: 'Footbridge', description: 'Footbridge at Whangarie Falls', creator_id: user3.id)
file15 = open('https://perfectpx-seeds.s3.amazonaws.com/whangarie_falls_footbridge.jpg')
px15.px.attach(io: file15, filename: 'whangarie_falls_footbridge.jpg')
comment71 = Comment.create!(user_id: user7.id, photo_id: px15.id, body: 'Beautiful photo')
comment72 = Comment.create!(user_id: user2.id, photo_id: px15.id, body: 'Beautiful light and colors.')
comment73 = Comment.create!(user_id: user9.id, photo_id: px15.id, body: 'Outstanding image')
comment74 = Comment.create!(user_id: user12.id, photo_id: px15.id, body: 'wonderful capture!!!')
comment75 = Comment.create!(user_id: user4.id, photo_id: px15.id, body: 'Perfect shot')

px16 = Photo.create!(title: 'Frozen Village', description: 'Winter village in Norway', creator_id: user4.id)
file16 = open('https://perfectpx-seeds.s3.amazonaws.com/norway_village.jpg')
px16.px.attach(io: file16, filename: 'norway_village.jpg')
comment76 = Comment.create!(user_id: user9.id, photo_id: px16.id, body: 'Great shot!')
comment77 = Comment.create!(user_id: user7.id, photo_id: px16.id, body: 'Fabulous capture')
comment78 = Comment.create!(user_id: user11.id, photo_id: px16.id, body: 'Beautiful colors, this shot is simply excellent!')
comment79 = Comment.create!(user_id: user1.id, photo_id: px16.id, body: 'Wonderful colors, Perfect light and mood! Very nice!')
comment80 = Comment.create!(user_id: user3.id, photo_id: px16.id, body: 'Impressive view and scenery!')

px17 = Photo.create!(title: 'Nightlight', description: 'USA at night from space', creator_id: user5.id)
file17 = open('https://perfectpx-seeds.s3.amazonaws.com/usa_at_night.jpg')
px17.px.attach(io: file17, filename: 'usa_at_night.jpg')
comment81 = Comment.create!(user_id: user2.id, photo_id: px17.id, body: 'Great timing!')
comment82 = Comment.create!(user_id: user8.id, photo_id: px17.id, body: 'Outstanding!')
comment83 = Comment.create!(user_id: user6.id, photo_id: px17.id, body: 'Looks flat to me')
comment84 = Comment.create!(user_id: user10.id, photo_id: px17.id, body: 'Uncommon view')
comment85 = Comment.create!(user_id: user1.id, photo_id: px17.id, body: 'Impressive view and scenery!')

px18 = Photo.create!(title: 'Wave', description: 'Shot of small wave on ocean surface', creator_id: user6.id)
file18 = open('https://perfectpx-seeds.s3.amazonaws.com/ocean_wave.jpg')
px18.px.attach(io: file18, filename: 'ocean_wave.jpg')
comment86 = Comment.create!(user_id: user7.id, photo_id: px18.id, body: 'Great comp')
comment87 = Comment.create!(user_id: user11.id, photo_id: px18.id, body: 'Amazing shot')
comment88 = Comment.create!(user_id: user5.id, photo_id: px18.id, body: 'Fabulous capture')
comment89 = Comment.create!(user_id: user2.id, photo_id: px18.id, body: 'Exellent capture and colors.')
comment90 = Comment.create!(user_id: user3.id, photo_id: px18.id, body: 'Wonderful capture:)')

px19 = Photo.create!(title: 'Leaves', description: 'Green-blue leaves', creator_id: user7.id)
file19 = open('https://perfectpx-seeds.s3.amazonaws.com/green_blue_leaves.jpg')
px19.px.attach(io: file19, filename: 'green_blue_leaves.jpg')
comment91 = Comment.create!(user_id: user4.id, photo_id: px19.id, body: 'Very Beautiful. Have a nice day my friend.')
comment92 = Comment.create!(user_id: user6.id, photo_id: px19.id, body: 'Beautiful POV and capture')
comment93 = Comment.create!(user_id: user10.id, photo_id: px19.id, body: 'Truly impressed with your attention catching photograph')
comment94 = Comment.create!(user_id: user12.id, photo_id: px19.id, body: 'Great scene')
comment95 = Comment.create!(user_id: user8.id, photo_id: px19.id, body: 'Superb shot')

px20 = Photo.create!(title: 'Ferns', description: 'Sea of green ferns', creator_id: user8.id)
file20 = open('https://perfectpx-seeds.s3.amazonaws.com/green_ferns.jpg')
px20.px.attach(io: file20, filename: 'green_ferns.jpg')
comment96 = Comment.create!(user_id: user9.id, photo_id: px20.id, body: 'Magnificent picture excellent work')
comment97 = Comment.create!(user_id: user3.id, photo_id: px20.id, body: 'Magnificent photo!')
comment98 = Comment.create!(user_id: user11.id, photo_id: px20.id, body: 'Wonderful light and view​, amazing capture​')
comment99 = Comment.create!(user_id: user5.id, photo_id: px20.id, body: 'Great shot, beautiful edit')
comment100 = Comment.create!(user_id: user1.id, photo_id: px20.id, body: 'Excellent shot')

px21 = Photo.create!(title: 'Eye', description: 'Architectural eye', creator_id: user9.id)
file21 = open('https://perfectpx-seeds.s3.amazonaws.com/architectural_eye.jpg')
px21.px.attach(io: file21, filename: 'architectural_eye.jpg')
comment101 = Comment.create!(user_id: user2.id, photo_id: px21.id, body: 'Exquisite composition!')
comment102 = Comment.create!(user_id: user4.id, photo_id: px21.id, body: 'Beautifully done! ')
comment103 = Comment.create!(user_id: user10.id, photo_id: px21.id, body: 'Stunning capture')
comment104 = Comment.create!(user_id: user7.id, photo_id: px21.id, body: 'Outstanding work!')
comment105 = Comment.create!(user_id: user3.id, photo_id: px21.id, body: 'Awesome perspective!')

px22 = Photo.create!(title: 'Beach Drive', description: 'Audi driving down beach-side road', creator_id: user10.id)
file22 = open('https://perfectpx-seeds.s3.amazonaws.com/audi_beach.jpg')
px22.px.attach(io: file22, filename: 'audi_beach.jpg')
comment106 = Comment.create!(user_id: user8.id, photo_id: px22.id, body: 'Everything perfect about the photo.')
comment107 = Comment.create!(user_id: user7.id, photo_id: px22.id, body: 'Great work')
comment108 = Comment.create!(user_id: user12.id, photo_id: px22.id, body: 'Very nice shot')
comment109 = Comment.create!(user_id: user2.id, photo_id: px22.id, body: 'So beautiful')
comment110 = Comment.create!(user_id: user9.id, photo_id: px22.id, body: 'Wow. Love the energy!')

px23 = Photo.create!(title: 'Bear', description: 'Big brown bear', creator_id: user11.id)
file23 = open('https://perfectpx-seeds.s3.amazonaws.com/brown_bear.jpg')
px23.px.attach(io: file23, filename: 'brown_bear.jpg')
comment111 = Comment.create!(user_id: user12.id, photo_id: px23.id, body: 'Really stunning capture')
comment112 = Comment.create!(user_id: user6.id, photo_id: px23.id, body: 'Just perfect')
comment113 = Comment.create!(user_id: user2.id, photo_id: px23.id, body: 'Very beautiful light and excellent shot')
comment114 = Comment.create!(user_id: user7.id, photo_id: px23.id, body: 'Nice shot!')
comment115 = Comment.create!(user_id: user4.id, photo_id: px23.id, body: 'Excellent shot')

px24 = Photo.create!(title: 'Dolphins', description: 'Small pod of three dolphins', creator_id: user12.id)
file24 = open('https://perfectpx-seeds.s3.amazonaws.com/triple_dolphins.jpg')
px24.px.attach(io: file24, filename: 'triple_dolphins.jpg')
comment116 = Comment.create!(user_id: user8.id, photo_id: px24.id, body: 'The colors are so vibrant')
comment117 = Comment.create!(user_id: user5.id, photo_id: px24.id, body: 'Wonderful shot and tones!')
comment118 = Comment.create!(user_id: user6.id, photo_id: px24.id, body: 'It''s a beautiful capture')
comment119 = Comment.create!(user_id: user12.id, photo_id: px24.id, body: 'Excellent work!')
comment120 = Comment.create!(user_id: user3.id, photo_id: px24.id, body: 'Beautiful image!')

px25 = Photo.create!(title: 'Winding Road', description: 'Road winding through a forest', creator_id: user1.id)
file25 = open('https://perfectpx-seeds.s3.amazonaws.com/winding_road.jpg')
px25.px.attach(io: file25, filename: 'winding_road.jpg')
comment121 = Comment.create!(user_id: user7.id, photo_id: px25.id, body: 'Outstanding')
comment122 = Comment.create!(user_id: user3.id, photo_id: px25.id, body: 'Beautiful work!')
comment123 = Comment.create!(user_id: user12.id, photo_id: px25.id, body: 'Excellent shot')
comment124 = Comment.create!(user_id: user2.id, photo_id: px25.id, body: 'Brilliant shot dear friend')
comment125 = Comment.create!(user_id: user4.id, photo_id: px25.id, body: 'Impressive photo')

px26 = Photo.create!(title: 'Giraffe Head', description: 'Just the tip', creator_id: user2.id)
file26 = open('https://perfectpx-seeds.s3.amazonaws.com/giraffe_head.jpg')
px26.px.attach(io: file26, filename: 'giraffe_head.jpg')
comment126 = Comment.create!(user_id: user5.id, photo_id: px26.id, body: 'beautiful simplicity..')
comment127 = Comment.create!(user_id: user8.id, photo_id: px26.id, body: 'Nice!')
comment128 = Comment.create!(user_id: user11.id, photo_id: px26.id, body: 'Fabulous capture')
comment129 = Comment.create!(user_id: user9.id, photo_id: px26.id, body: 'Exellent work')
comment130 = Comment.create!(user_id: user1.id, photo_id: px26.id, body: 'Fantastic atmosphere with soft light!')

px27 = Photo.create!(title: 'Empire State', description: 'Empire State Building - NYC', creator_id: user3.id)
file27 = open('https://perfectpx-seeds.s3.amazonaws.com/empire_state_nyc.jpg')
px27.px.attach(io: file27, filename: 'empire_state_nyc.jpg')
comment131 = Comment.create!(user_id: user11.id, photo_id: px27.id, body: 'Wonderful composition!')
comment132 = Comment.create!(user_id: user2.id, photo_id: px27.id, body: 'Great lines')
comment133 = Comment.create!(user_id: user6.id, photo_id: px27.id, body: 'Nice shot')
comment134 = Comment.create!(user_id: user4.id, photo_id: px27.id, body: 'Stunning work, amazing composition')
comment135 = Comment.create!(user_id: user8.id, photo_id: px27.id, body: 'Marvelous picture')

px28 = Photo.create!(title: 'Kirkjufell', description: 'Kirkjufell - the "mountain shaped like an arrowhead".', creator_id: user4.id)
file28 = open('https://perfectpx-seeds.s3.amazonaws.com/arrowhead_mountain.jpg')
px28.px.attach(io: file28, filename: 'arrowhead_mountain.jpg')
comment136 = Comment.create!(user_id: user1.id, photo_id: px28.id, body: 'Really fantastic photo.')
comment137 = Comment.create!(user_id: user10.id, photo_id: px28.id, body: 'Amazing shot! Beautiful colors, light and composition!')
comment138 = Comment.create!(user_id: user11.id, photo_id: px28.id, body: 'Wooo amazing work so beautiful')
comment139 = Comment.create!(user_id: user2.id, photo_id: px28.id, body: 'Great mood and compositon!')
comment140 = Comment.create!(user_id: user7.id, photo_id: px28.id, body: 'Wonderful capture and beautiful mood')

px29 = Photo.create!(title: 'Yak', description: 'Young yak', creator_id: user5.id)
file29 = open('https://perfectpx-seeds.s3.amazonaws.com/young_moo.jpg')
px29.px.attach(io: file29, filename: 'young_moo.jpg')
comment141 = Comment.create!(user_id: user11.id, photo_id: px29.id, body: 'An excellent animal portrait with a very good pose and very pretty colors!')
comment142 = Comment.create!(user_id: user9.id, photo_id: px29.id, body: 'Beautiful')
comment143 = Comment.create!(user_id: user10.id, photo_id: px29.id, body: 'An absolutely spectacular image my friend')
comment144 = Comment.create!(user_id: user4.id, photo_id: px29.id, body: 'Beautiful shot')
comment145 = Comment.create!(user_id: user2.id, photo_id: px29.id, body: 'Wonderful colours and a fantastic atmosphere.')

px30 = Photo.create!(title: 'Commute', description: 'Aerial view of city showing lit up roadways', creator_id: user6.id)
file30 = open('https://perfectpx-seeds.s3.amazonaws.com/city_aerial.jpg')
px30.px.attach(io: file30, filename: 'city_aerial.jpg')
comment146 = Comment.create!(user_id: user5.id, photo_id: px30.id, body: 'A superb composition, very fine art!')
comment147 = Comment.create!(user_id: user1.id, photo_id: px30.id, body: 'Excellent, my friend!')
comment148 = Comment.create!(user_id: user2.id, photo_id: px30.id, body: 'Exceptional.. extraordinary.. magnificent work')
comment149 = Comment.create!(user_id: user10.id, photo_id: px30.id, body: 'Outstanding work!')
comment150 = Comment.create!(user_id: user3.id, photo_id: px30.id, body: 'Beautiful composition and mood ')

px31 = Photo.create!(title: 'Jelly Fish', description: 'Cool jelly fish from the deep', creator_id: user7.id)
file31 = open('https://perfectpx-seeds.s3.amazonaws.com/jelly_fish.jpg')
px31.px.attach(io: file31, filename: 'jelly_fish.jpg')
comment151 = Comment.create!(user_id: user2.id, photo_id: px31.id, body: 'What a spectacular image')
comment152 = Comment.create!(user_id: user9.id, photo_id: px31.id, body: 'congrats on the amazing shot!')
comment153 = Comment.create!(user_id: user12.id, photo_id: px31.id, body: 'Beautiful jelly fish!')
comment154 = Comment.create!(user_id: user6.id, photo_id: px31.id, body: 'Amazing capture!')
comment155 = Comment.create!(user_id: user11.id, photo_id: px31.id, body: 'Lovely work')

px32 = Photo.create!(title: 'Peek', description: 'Cat peeking over roof', creator_id: user8.id)
file32 = open('https://perfectpx-seeds.s3.amazonaws.com/cat_on_roof.jpg')
px32.px.attach(io: file32, filename: 'cat_on_roof.jpg')
comment156 = Comment.create!(user_id: user10.id, photo_id: px32.id, body: 'Cute!')
comment157 = Comment.create!(user_id: user1.id, photo_id: px32.id, body: 'Beautiful light and colour,stunning capture')
comment158 = Comment.create!(user_id: user4.id, photo_id: px32.id, body: 'Beautifully taken image')
comment159 = Comment.create!(user_id: user2.id, photo_id: px32.id, body: 'Brilliant.. outstanding work')
comment160 = Comment.create!(user_id: user6.id, photo_id: px32.id, body: 'marvelous photo')

px33 = Photo.create!(title: 'Stumps', description: 'Just some tree stumps', creator_id: user9.id)
file33 = open('https://perfectpx-seeds.s3.amazonaws.com/tree_logs.jpg')
px33.px.attach(io: file33, filename: 'tree_logs.jpg')
comment161 = Comment.create!(user_id: user2.id, photo_id: px33.id, body: 'Love this one')
comment162 = Comment.create!(user_id: user4.id, photo_id: px33.id, body: 'Nicely done!')
comment163 = Comment.create!(user_id: user6.id, photo_id: px33.id, body: 'Excellent perspective')
comment164 = Comment.create!(user_id: user8.id, photo_id: px33.id, body: 'Fantastic work!')
comment165 = Comment.create!(user_id: user10.id, photo_id: px33.id, body: 'On top of the world :-)')

px34 = Photo.create!(title: 'Angles', description: 'Geometric shapes from two adjacent buildings', creator_id: user10.id)
file34 = open('https://perfectpx-seeds.s3.amazonaws.com/adjacent_buildings.jpg')
px34.px.attach(io: file34, filename: 'adjacent_buildings.jpg')
comment166 = Comment.create!(user_id: user1.id, photo_id: px34.id, body: 'Wonderful shooting!')
comment167 = Comment.create!(user_id: user3.id, photo_id: px34.id, body: 'Stunning')
comment168 = Comment.create!(user_id: user5.id, photo_id: px34.id, body: 'Great angles!')
comment169 = Comment.create!(user_id: user7.id, photo_id: px34.id, body: 'Wonderful view and amazing capture.​')
comment170 = Comment.create!(user_id: user9.id, photo_id: px34.id, body: 'Great lighting and colors')

px35 = Photo.create!(title: 'Lightshow', description: 'The Northern Lights', creator_id: user11.id)
file35 = open('https://perfectpx-seeds.s3.amazonaws.com/northern_lights.jpg')
px35.px.attach(io: file35, filename: 'northern_lights.jpg')
comment171 = Comment.create!(user_id: user12.id, photo_id: px35.id, body: 'Amazing sky and stunning capture​')
comment172 = Comment.create!(user_id: user10.id, photo_id: px35.id, body: 'It is so good that i cant say anything.')
comment173 = Comment.create!(user_id: user8.id, photo_id: px35.id, body: 'Interesting moment masterfully captured')
comment174 = Comment.create!(user_id: user6.id, photo_id: px35.id, body: 'Awesome capture. Fabulous photography')
comment175 = Comment.create!(user_id: user4.id, photo_id: px35.id, body: 'Wonderful photo and work')

px36 = Photo.create!(title: 'Beach Day', description: 'Aerial shot of crowded beach', creator_id: user12.id)
file36 = open('https://perfectpx-seeds.s3.amazonaws.com/beach_aerial.jpg')
px36.px.attach(io: file36, filename: 'beach_aerial.jpg')
comment176 = Comment.create!(user_id: user1.id, photo_id: px36.id, body: 'Amazing photo! Beautiful!')
comment177 = Comment.create!(user_id: user4.id, photo_id: px36.id, body: 'Impressive scenery and atmosphere! Excellent photo!')
comment178 = Comment.create!(user_id: user7.id, photo_id: px36.id, body: 'Wonderful scenery my friend!')
comment179 = Comment.create!(user_id: user10.id, photo_id: px36.id, body: 'Incredible atmosphere!')
comment180 = Comment.create!(user_id: user11.id, photo_id: px36.id, body: 'Beautiful shot, my friend!')

px37 = Photo.create!(title: 'Abandoned', description: 'Plane abandoned in the middle of the forest', creator_id: user1.id)
file37 = open('https://perfectpx-seeds.s3.amazonaws.com/abandoned_plane.jpg')
px37.px.attach(io: file37, filename: 'abandoned_plane.jpg')
comment181 = Comment.create!(user_id: user2.id, photo_id: px37.id, body: 'Very beautiful photography!')
comment182 = Comment.create!(user_id: user5.id, photo_id: px37.id, body: 'Fine work!!! Well done')
comment183 = Comment.create!(user_id: user8.id, photo_id: px37.id, body: 'Very Great photo!')
comment184 = Comment.create!(user_id: user11.id, photo_id: px37.id, body: 'Stunning capture')
comment185 = Comment.create!(user_id: user12.id, photo_id: px37.id, body: 'Very Beautiful. Have a nice day my friend.')

px38 = Photo.create!(title: 'Balcony Gardens', description: 'Building with balcony gardens', creator_id: user2.id)
file38 = open('https://perfectpx-seeds.s3.amazonaws.com/balcony_gardens.jpg')
px38.px.attach(io: file38, filename: 'balcony_gardens.jpg')
comment186 = Comment.create!(user_id: user12.id, photo_id: px38.id, body: 'Excellent work')
comment187 = Comment.create!(user_id: user9.id, photo_id: px38.id, body: 'Wonderful lighting')
comment188 = Comment.create!(user_id: user6.id, photo_id: px38.id, body: 'So beautiful coloring! Fantastic composition!')
comment189 = Comment.create!(user_id: user3.id, photo_id: px38.id, body: 'Excellent composition and wonderful color tone!')
comment190 = Comment.create!(user_id: user1.id, photo_id: px38.id, body: 'Such amazing and cool image')

px39 = Photo.create!(title: 'Flatiron Building', description: 'Flatiron Building - NYC', creator_id: user3.id)
file39 = open('https://perfectpx-seeds.s3.amazonaws.com/flatiron_building.jpg')
px39.px.attach(io: file39, filename: 'flatiron_building.jpg')
comment191 = Comment.create!(user_id: user11.id, photo_id: px39.id, body: 'Great angle')
comment192 = Comment.create!(user_id: user8.id, photo_id: px39.id, body: 'Wonderful lighting')
comment193 = Comment.create!(user_id: user5.id, photo_id: px39.id, body: 'Brilliant picture')
comment194 = Comment.create!(user_id: user2.id, photo_id: px39.id, body: 'Sweet work! Well done')
comment195 = Comment.create!(user_id: user1.id, photo_id: px39.id, body: 'This shot is really fabulous')

px40 = Photo.create!(title: 'Penguins', description: 'Penguins in the arctic', creator_id: user4.id)
file40 = open('https://perfectpx-seeds.s3.amazonaws.com/penguins.jpg')
px40.px.attach(io: file40, filename: 'penguins.jpg')
comment196 = Comment.create!(user_id: user1.id, photo_id: px40.id, body: 'Great composition!')
comment197 = Comment.create!(user_id: user6.id, photo_id: px40.id, body: 'Nice I really like this!')
comment198 = Comment.create!(user_id: user11.id, photo_id: px40.id, body: 'Lovely and creative.')
comment199 = Comment.create!(user_id: user5.id, photo_id: px40.id, body: 'Love it fabulous shot')
comment200 = Comment.create!(user_id: user9.id, photo_id: px40.id, body: 'A great photographer')

px41 = Photo.create!(title: 'Eiffel Tower', description: 'Eiffel Tower - Paris, France', creator_id: user5.id)
file41 = open('https://perfectpx-seeds.s3.amazonaws.com/eiffel_tower.jpg')
px41.px.attach(io: file41, filename: 'eiffel_tower.jpg')
comment201 = Comment.create!(user_id: user12.id, photo_id: px41.id, body: 'Beautiful architecture!')
comment202 = Comment.create!(user_id: user8.id, photo_id: px41.id, body: 'So good')
comment203 = Comment.create!(user_id: user4.id, photo_id: px41.id, body: 'Amazing shot')
comment204 = Comment.create!(user_id: user1.id, photo_id: px41.id, body: 'So good')
comment205 = Comment.create!(user_id: user9.id, photo_id: px41.id, body: 'Beautiful B/W composition work!')

px42 = Photo.create!(title: 'Elephants', description: 'Two elephants standing around', creator_id: user6.id)
file42 = open('https://perfectpx-seeds.s3.amazonaws.com/elephants.jpg')
px42.px.attach(io: file42, filename: 'elephants.jpg')
comment206 = Comment.create!(user_id: user1.id, photo_id: px42.id, body: 'Fantastic portrait with beautiful colors and details!')
comment207 = Comment.create!(user_id: user10.id, photo_id: px42.id, body: 'Incredible perfection and incredible beauty')
comment208 = Comment.create!(user_id: user7.id, photo_id: px42.id, body: 'so splendid brilliant and detailed')
comment209 = Comment.create!(user_id: user4.id, photo_id: px42.id, body: 'Spectacular shot!')
comment210 = Comment.create!(user_id: user2.id, photo_id: px42.id, body: 'Very beautiful photography')

px43 = Photo.create!(title: 'Golden Sun', description: 'Sunflower shot during golden hour', creator_id: user7.id)
file43 = open('https://perfectpx-seeds.s3.amazonaws.com/golden_hour_sunflower.jpg')
px43.px.attach(io: file43, filename: 'golden_hour_sunflower.jpg')
comment211 = Comment.create!(user_id: user12.id, photo_id: px43.id, body: 'Marvelous light and pov! Beautiful night scene!')
comment212 = Comment.create!(user_id: user3.id, photo_id: px43.id, body: 'Brilliant capture')
comment213 = Comment.create!(user_id: user6.id, photo_id: px43.id, body: 'Phenomenal photography!')
comment214 = Comment.create!(user_id: user11.id, photo_id: px43.id, body: 'This is awesome. Fabulous shot')
comment215 = Comment.create!(user_id: user4.id, photo_id: px43.id, body: 'Wow the detailing.. amazing click')

px44 = Photo.create!(title: 'Peeking Deer', description: 'Deer peeking out from the bushes', creator_id: user8.id)
file44 = open('https://perfectpx-seeds.s3.amazonaws.com/peeking_deer.jpg')
px44.px.attach(io: file44, filename: 'peeking_deer.jpg')
comment216 = Comment.create!(user_id: user6.id, photo_id: px44.id, body: 'So beautiful and elegant portrait!')
comment217 = Comment.create!(user_id: user9.id, photo_id: px44.id, body: 'Fantastic coloring tone and atmosphere!')
comment218 = Comment.create!(user_id: user12.id, photo_id: px44.id, body: 'Excellent shot!')
comment219 = Comment.create!(user_id: user3.id, photo_id: px44.id, body: 'Great work')
comment220 = Comment.create!(user_id: user5.id, photo_id: px44.id, body: 'Excellent work my friend!')

px45 = Photo.create!(title: 'Warp', description: 'Escalator', creator_id: user9.id)
file45 = open('https://perfectpx-seeds.s3.amazonaws.com/escalator.jpg')
px45.px.attach(io: file45, filename: 'escalator.jpg')
comment221 = Comment.create!(user_id: user7.id, photo_id: px45.id, body: 'Incredible photography')
comment222 = Comment.create!(user_id: user11.id, photo_id: px45.id, body: 'Wonderful atmosphere')
comment223 = Comment.create!(user_id: user3.id, photo_id: px45.id, body: 'Nice composition! Your pic is amazing!')
comment224 = Comment.create!(user_id: user5.id, photo_id: px45.id, body: 'Beautiful work')
comment225 = Comment.create!(user_id: user10.id, photo_id: px45.id, body: 'Excellent composition and wonderful color tone!')

px46 = Photo.create!(title: 'Hairpin', description: 'Hairpin turn in the middle of the forest', creator_id: user10.id)
file46 = open('https://perfectpx-seeds.s3.amazonaws.com/hairpin_turn.jpg')
px46.px.attach(io: file46, filename: 'hairpin_turn.jpg')
comment226 = Comment.create!(user_id: user7.id, photo_id: px46.id, body: 'Simply gorgeous')
comment227 = Comment.create!(user_id: user8.id, photo_id: px46.id, body: 'Fantastic scenery! Excellent photo!')
comment228 = Comment.create!(user_id: user9.id, photo_id: px46.id, body: 'Stunning work my friend')
comment229 = Comment.create!(user_id: user3.id, photo_id: px46.id, body: 'Beautiful!!!')
comment230 = Comment.create!(user_id: user5.id, photo_id: px46.id, body: 'Outstanding')

px47 = Photo.create!(title: 'Winter Ferrari', description: 'Ferrari in the snow', creator_id: user11.id)
file47 = open('https://perfectpx-seeds.s3.amazonaws.com/ferrari_in_snow.jpg')
px47.px.attach(io: file47, filename: 'ferrari_in_snow.jpg')
comment231 = Comment.create!(user_id: user3.id, photo_id: px47.id, body: 'Wonderful light and view​, amazing capture​')
comment232 = Comment.create!(user_id: user5.id, photo_id: px47.id, body: 'Wonderful frame, light and colors !')
comment233 = Comment.create!(user_id: user7.id, photo_id: px47.id, body: 'Great mood')
comment234 = Comment.create!(user_id: user2.id, photo_id: px47.id, body: 'Excellent work')
comment235 = Comment.create!(user_id: user9.id, photo_id: px47.id, body: 'Beautiful light and coloring tone!')

px48 = Photo.create!(title: 'Do What You Love', description: 'Neon sign', creator_id: user12.id)
file48 = open('https://perfectpx-seeds.s3.amazonaws.com/what_you_love.jpg')
px48.px.attach(io: file48, filename: 'what_you_love.jpg')
comment236 = Comment.create!(user_id: user4.id, photo_id: px48.id, body: 'Stunning light! Great photo')
comment237 = Comment.create!(user_id: user2.id, photo_id: px48.id, body: 'Awesome capture')
comment238 = Comment.create!(user_id: user6.id, photo_id: px48.id, body: 'Fantastic!')
comment239 = Comment.create!(user_id: user8.id, photo_id: px48.id, body: 'An absolutely powerful image')
comment240 = Comment.create!(user_id: user10.id, photo_id: px48.id, body: 'Superb work.')

# px = Photo.create!(title: '', description: '', creator_id: user1.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user2.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user3.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user4.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user5.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user6.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user7.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user8.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user9.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user10.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user11.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user12.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user1.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user2.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user3.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user4.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user5.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user6.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user7.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user8.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user9.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user10.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user11.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user12.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user1.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user2.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user3.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user4.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user5.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user6.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user7.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user8.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user9.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user10.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user11.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user12.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user1.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user2.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user3.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user4.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user5.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user6.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user7.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user8.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user9.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user10.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user11.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )

# px = Photo.create!(title: '', description: '', creator_id: user12.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )



# px = Photo.create!(title: '', description: '', creator_id: user.id)
# file = open('')
# px.px.attach(io: file, filename: '')
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )
# comment = Comment.create!(body: '', user_id: , photo_id: )